### ISSUE TITLE
Incomplete API doc snippet shown for publishMessage function from NATS client

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-standard-library#1144]
**Description:**
When hovering over publishMessage function, I am seeing an incomplete API documentation for the function as below.

<img width="693" alt="Screenshot 2021-03-23 at 15 52 17" src="https://user-images.githubusercontent.com/690559/112131710-d7dd9600-8bef-11eb-8d6f-0c2306fb3013.png">

```
Publishes data to a given subject.

ballerina # nats:Error? result = natsClient->publishMessage(<@untainted>message); #

Parameters
nats:Message message : Message to be published

Returns
nats:Error?() or else a nats:Error if there is a problem when publishing the message
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by aashikam** [comment]
Checked in Ballerina Swan Lake Beta 1
Closing since the issue seems to be resolved. 
Hovering over `publishMessage` prompts the following: 
<img width="557" alt="Screenshot 2021-06-10 at 09 26 55" src="https://user-images.githubusercontent.com/39673615/121462299-076d9480-c9ce-11eb-8ea9-e1366d5cda29.png">
