### ISSUE TITLE
Look into inconsistencies in timestamp retrieval through data clients

### ISSUE THREAD

**Issue by Manuri** [ballerina-platform/ballerina-standard-library#129]
**Description:**
There seem to inconsistencies in timestamp retrieval. Check for the following.

1. Differences in when iterating the data in a loop and JSON conversion
2. Asymmetry in insertion and retrieval - when inserting we convert to UTC. When retrieving seems the timestamp is not converted to current timestamp.

**Comment by lahirusamith** [comment]
@daneshk @niveathika It seems that different java connectors giving different ResultSet  values for  java.sql.Timestamp in different databases. this is happening for java.sql.Time and java.sql.Dates as well. since jballerina Result conversion depends on SQL type and the ResultSet Value, need to come up with a proper way to address this issue.

**Comment by daneshk** [comment]
are we still getting this inconsistency when we deal only with UTC timestamp. Looks like `postgres` db returns weird output for `CallableStatements`?

**Comment by lahirusamith** [comment]
This issue has been fixed. But in order to close the issue, a test should be run for all databases to verify.

**Comment by daneshk** [comment]
This issue is tested and verified on all supported DB connectors. Hense closing the issue
