### ISSUE TITLE
Getting a Null Pointer Exception when trying to get response payload as a stream.

### ISSUE THREAD

**Issue by sachinira** [ballerina-platform/ballerina-standard-library#1333]
**Description:**
I'm trying to get the content of an image using a ballerina code as a stream<byte[]>. But when  acessing the stream it gives me a null pointer error.

**Steps to reproduce:**
The code which gives the error is as follows
```ballerina
import ballerina/http;
import ballerina/io;
import ballerina/log;
public function main() returns error? {
    http:Client httpClient = check new("https://www.tutorialspoint.com/java_dip/images");
    http:Response response = check httpClient->get("/digital_image_processing.jpg");
    byte[] content = check response.getBinaryPayload();
    if (response.statusCode is http:STATUS_OK) {
        stream<byte[],io:Error?>responseStream = check response.getByteStream();
        io:Error? e = responseStream.forEach(isolated function(byte[] bytes){
            io:println(bytes);
        });
    } else {
        json errorPayload = check response.getJsonPayload();
        string message = errorPayload.toString();
        log:printError(message);
    }
}
```
**Affected Versions:**
Ballerina SLAlpha 5

**OS, DB, other environment details and versions:**
Ubuntu 20.04 LTS
Ballerina SL Alpha 5
JDK 11

**Comment by chamil321** [comment]
The inbound response contains cache headers and the caching client build the data source to cache the response. Once the stream is consumed once, it cannot be reused. Hence user has to use built payload (byte[]) to proceed. Otherwise caching can be disabled to avoid payload being built internally.

The NPE is fixed via https://github.com/ballerina-platform/module-ballerina-http/pull/374
