### ISSUE TITLE
HTTP endpoints should prepend `/` if not added

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-standard-library#1354]
**Description:**
```ballerina
    http:Client clientEndpoint = check new ("https://itunes.apple.com/");
    var serachResult = check clientEndpoint->get("search?term=kinks&entity=album&attribute=allArtistTerm");
```

above gave me `error("Could not resolve host:itunes.apple.comsearch")` this is not good UX, we should prepend `/` if not not given or give an error saying slash is not there.
also note that I do have the slash at the end of the host, but that didn't work.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by chamil321** [comment]
The issue was fixed by appending "/" to the resource path except for empty paths and paths starting with `/`, `?`, `#`.

```ballerina
    http:Client httpUrlClient = check new("http://localhost:9090/url"); 
    http:Response|error response = httpUrlClient->get("abc"); // this is allowed
```

This change does some manipulation to the URL which could lead to many problems in future. We do not know at which point user would break the URL and put two parts. 

Hence it's better if we could avoid such sanitisation
 - Remove ending `/`
 - Prepend starting `/`
 
@shafreenAnfar thoughts?

**Comment by shafreenAnfar** [comment]
Yeah, I also believe if we could get rid of such sanitization, it would be good. I think if base-path dispatching logic works without any issue, as you mentioned we should get rid of it.
