### ISSUE TITLE
Connection pool does not get recovered after being exhausted 

### ISSUE THREAD

**Issue by Bhashinee** [ballerina-platform/ballerina-standard-library#1356]
**Description:**
Carried out a load test as follows,
1. Passthrough service. Please note that `maxActiveConnections` is limited to 100 in the `clientEP2`.
```ballerina
import ballerina/http;
import ballerina/log;

http:Client clientEP = new ("http://localhost:9097/Hello");
http:Client clientEP2 = new ("https://localhost:9098/Hello", {
    secureSocket: {
        trustStore: {
            path:"/home/bhashinee/ballerina_home/bre/security/ballerinaTruststore.p12",
            password: "ballerina"
        }
    },
    poolConfig: { maxActiveConnections: 100 }
});

service Hello on new http:Listener(9090) {
    @http:ResourceConfig {
        path: "/sayHello"
    }
    resource function passthrough(http:Caller caller, http:Request req) {
        future<()> publishedEvent = start publishSecondEvent();
        var clientResponse = clientEP->forward("/sayHello", req);
        if (clientResponse is http:Response) {
            var result = caller->respond(clientResponse);
            if (result is error) {
                log:printError("Error sending response", result);
            }
        } else {
            http:Response res = new;
            res.statusCode = 500;
            res.setTextPayload(<string>clientResponse.detail()?.message);
            var result = caller->respond(res);
            if (result is error) {
                log:printError("Error sending response", result);
            }
        }
    }
}

public function publishSecondEvent() {
    http:Request clientRequest = new;
    clientRequest.setTextPayload("Hello World");
    var response = clientEP2->post("/sayHello", clientRequest);
    if (response is http:Response) {
        log:printDebug("Second request sent.");
    } else {
        log:printError(response.reason(), err = response);
    }
}

```

2. Backend service
```ballerina
import ballerina/http;
service Hello on new http:Listener(9097) {
    resource function sayHello(http:Caller caller,
        http:Request req) returns error? {
        check caller->respond("Hello, World!");
    }
}
```
3. Async back-end called by the code line `future<()> publishedEvent = start publishSecondEvent();` in the passthrough service.
```ballerina
import ballerina/http;

http:ListenerConfiguration helloWorldEPConfig = {
    secureSocket: {
        keyStore: {
            path: "/home/bhashinee/ballerina_home/bre/security/ballerinaKeystore.p12",
            password: "ballerina"
        }
    }
};

service Hello on new http:Listener(9098, config = helloWorldEPConfig) {
    resource function sayHello(http:Caller caller,
        http:Request req) returns error? {
        check caller->respond("Hello, World! - 2");
    }
}
```
4. Run the passthrough service after reducing the Java Heap memory size to 256m. 
5. Send post requests with the payload `{hello :world}` with 50 concurrencies from JMeter to passthrough service.

***Observation***
Test run with 0 errors for the first 10 - 15 minutes and then gives the error
`Could not obtain a connection within maximum wait time` when calling the Async endpoint continuously.

Stopped sending requests for about 10 minutes(to give time for the connection pool to get recovered). Then sent a few requests like 10 and could observe that the same error continues to pop up.

Suspected code segment: https://github.com/ballerina-platform/module-ballerina-http/blob/master/http-native/src/main/java/org/ballerinalang/net/transport/contractimpl/sender/channel/pool/ConnectionManager.java#L194

**Affected Versions:**
Tests were followed in ballerina-1.1.6.

**OS, DB, other environment details and versions:**
Ballerina 1.1.6 reducing the xmx to 256m

**Comment by chamil321** [comment]
### Observation:

This is reproducible with Swan lake beta 2. 

During the execution, 2 backend are invoked using 2 clients. Each will  create separate GenericObjectPool for each route. Once the execution is done, target channel is returned to the pool.

```
srcHlrConnPool: http-localhost-9098-1066558649-9dfc7f2b-377d-4eee-b7ec-6ea0757ef7dd : 1
srcHlrConnPool: http-127.0.0.1-9097-1066558649-b32e67aa-581d-46db-ba27-dbc98160f3c2 : 2

returnChannel: http-localhost-9098-1066558649-9dfc7f2b-377d-4eee-b7ec-6ea0757ef7dd
returnChannel: http-127.0.0.1-9097-1066558649-b32e67aa-581d-46db-ba27-dbc98160f3c2
```

[Invalidation is called](
https://github.com/ballerina-platform/module-ballerina-http/blob/v1.1.0-beta.2/http-native/src/main/java/org/ballerinalang/net/transport/contractimpl/sender/channel/pool/ConnectionManager.java#L194) only if the GenericPoolObject is idle for 5 mins or connection is closed.

**Comment by TharmiganK** [comment]
Reduced the `maxActiveConnections` to 10 and send 5 concurrent requests and observed that intermittently the target channel connection for async backend(9098) is neither returned to the pool after returning the response, nor invalidated after target channel inactive. 

This is happened because the target pool map in source handler was cleared after source handler channel inactive. This target pool map contained both target channel connections for sync backend(9097) and async backend(9098). 

But ideally the connection for the async call should be created from the global pool and should not be correlated to a source handler.

```
Getting connection from pool : https-localhost-9098 : 982135376
Getting connection from pool : http-localhost-9097 : 1229855654
Returning connection to pool : http-localhost-9097 : 1229855654
SourceHandler : 282204946 channel inactive
SourceHandler : 282204946 correlated with TargetChannel : 982135376 has empty pool map
Inactive connection pool not returning : https-localhost-9099 : 982135376
```

**Comment by TharmiganK** [comment]
Tested the fix - [`Stop adding sourceHandler for async backend calls #821`](https://github.com/ballerina-platform/module-ballerina-http/pull/821) as follows :

1. Reduced the `maxActiveConnections` to 10 and sent 5 concurrent requests, and observed that all the connections created for sync backend(9097) and async backend(9098) were returned to the pool. Also for the async backend(9098), the connections were created from the global pool.

2. Sent 20 concurrent requests 4 times and observed that following error occurred for some requests : `Could not obtain a connection within maximum wait time` as expected since the `maxActiveConnections` is set to 10. Then given some idle time for the connection pool to get recovered. In this time some of the connections created for async backend(9098) were invalidated. Then again sent 5 concurrent requests and observed that **the above error did not pop up**.
