### ISSUE TITLE
Map error for 4XX and 5XX responses

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-standard-library#1402]
**Description:**
ATM following
```ballerina
http:Response res =  check backendClient->get("/backend/Response");
```
behaviour return `http:Response` for any backend response regardless of the status code. Change it to only for success response and $subject.
                                                
> Handle No content response status codes such as 100 -199 and 204 and 304
> Populate header to error details
> Return response phrase as `error.message()`
> Populate error response payload to the error detail

**Comment by chamil321** [comment]
> > Return response phrase as `error.message()`
> > Populate error response payload to the error detail

Having a reason phrase as the error message is quite redundant. Since you already have the status code in error, it better to have response payload as error.message(). 

IMO, the payload of the error response describes the proper reason for the failure. 
`"no matching resource found for path : /echo/message/echo/message , method : GET"`
It is the ideal map the error.message() where user can simply check the message and understand the cause.

With this approach, response body is set as anydata to the error detail, so when you access it, you need to do typeguard on it which complex a simple usecase.

```
if (resp is http:RemoteServerError) {
    resp.detail().statusCode;
    anydata body = resp.detail().body;
    if body is string {

    } else if body is json {

    } else if body is xml {

    }
}
```

On the other hand, a passthrough case would loose the detail significantly. For example, following is a response get from the passthrough service where backend sends 501. 
```
< HTTP/1.1 501 Not Implemented
< content-type: text/plain
< content-length: 15
< server: ballerina
< date: Sat, 29 May 2021 09:38:40 +0530
< 
* Connection #0 to host localhost left intact
Not Implemented
```

When middle service to backend client returns an RemoteServerError(5XX)/ClientRequestError(4XX) and middle service just do a check on the error, then user get just error.message() as response payload which is reason phrase. 

Pretty sure this will cost the user

**Comment by shafreenAnfar** [comment]
Interesting, Yeah, I agree when it comes to `text/plain`, passing the message as part of the error message makes sense and it is super convenient. 

However, I am just wondering what would happen if the data type is something else say `xml` or `json` which is quite common because most of the APIs use these two data structures. If we are to set these as part of the message, we have to convert the data into a string and send it over the wire. 

Which basically means any data structure would go over wire as `text/plain`. This means users have to write additional code to handle errors in receiving end.

This is true for the second scenario as well. Because it would look like the below,

**Error Scenario** 
backend (application/json) -> middle server (text/plain) -> frontend 

**Success Scenario**
backend (application/json) -> middle server (application/json) -> frontend 

>When middle service to backend client returns an RemoteServerError(5XX)/ClientRequestError(4XX) and middle service just do a check on the error, then user get just error.message() as response payload which is reason phrase.

In this case, I feel we need to improve our serializers and deserializers. It should work like this,

wire message (1) -> deserializer (2) -> ballerina error message (3) 
ballerina error message (3) -> serializer (4) -> wire message (5)

wire message (1) = wire message (5)

This is similar to serializer/deserializer we have for `http:Response` or `http:Request`.

Lastly, doing so, is inconvenient compared to what we have in the case of `text/plain` but the same inconvenience is there in the current approach when it comes to other data structures.

```ballerina
if (resp is http:RemoteServerError) {
    resp.detail().statusCode;
    anydata body = resp.detail().body;
    if body is string {

    } 
}
```
Maybe we can come with some util methods to help with this. 

Therefore, while I agree, there is some inconvenience associated with passing the body as part of the data record,  all in all, I believe, passing the body as part of the data record is better than making it a part of the error message.

 Wouldn't that be the case or do you see it differently ?

**Comment by chamil321** [comment]
+1. The data loss will fade away with the serialisation.

**Comment by chamil321** [comment]
The inital PR was reverted and added the following requirements
> Handle No content response status codes such as 100 -199 and 204 and 304
> Populate header to error details
> Return response phrase as `error.message()`
> Populate error response payload to the error detail

via https://github.com/ballerina-platform/module-ballerina-http/pull/427
