### ISSUE TITLE
[Websub]No service matching found error when service listen on path /

### ISSUE THREAD

**Issue by MadhurangaWije** [ballerina-platform/ballerina-standard-library#1431]
**Description:**
When created a websub subscriber service as follows, which listen on path `/`, following error get thrown
`no matching service found for path : /`

![Screenshot from 2021-06-07 11-45-27](https://user-images.githubusercontent.com/27579184/120968145-1e21aa80-c786-11eb-94de-2f68cf15f8a1.png)

Sample code used,
```
import ballerina/websub;
import ballerina/io;

@websub:SubscriberServiceConfig {
    target: [
        "https://api.github.com/hub", 
        "https://github.com/MadhurangaWije/github-connector/events/*.json"
    ],
    secret: "<YOUR_SECRET_KEY>",
    callback: "<CALLBACK_URL>/",
    httpConfig: {
        auth: {
            token: "<ACCESS_TOKEN>"
        }
    }
}
service / on new websub:Listener(9090) {

    remote function onEventNotification(
                    websub:ContentDistributionMessage event){
        var retrievedContent = event.content;
        io:println(retrievedContent);
    }
}

```
Also tested by removing `/` from the service declaration, but still the same error occurs.

**Steps to reproduce:**

**Affected Versions:**
Ballerina Swan Lake Alpha 5

**OS, DB, other environment details and versions:**
Ubuntu 20.04, OpenJDK 11,

**Suggested Labels (optional):**
websub

**Suggested Assignees (optional):**

**Comment by ayeshLK** [comment]
* `callback` is an optional configuration in `websub:SubscriberServiceConfig` which is used to provide the callback-URL when we run the `websub:SubscriberService` behind a reverse-proxy or tcp-tunneling software (ngrok etc.). Therefore, is there a reason to use the callback in this case ?
* In current `websub` design we generate random unique URL path segment when `/` is provided as the service path. This decision was taken since `websub` has a security concern on the URLs that they should be [unguessable and unique](https://www.w3.org/TR/websub/#subscriber-sends-subscription-request). In addition to that, in websub this URL is also used as a form of authenticating the subscriber.

Therefore is there a special reason to go against websub recommendations ?

**Comment by MadhurangaWije** [comment]
No, actually there is no any special reason to specifically have only `/`, this concern was raised because, the previous versions supported to have `/`. We can follow-up with the suggested way then.
Thank you.
