### ISSUE TITLE
Implement declarative auth design for gRPC service

### ISSUE THREAD

**Issue by ldclakmal** [ballerina-platform/ballerina-standard-library#1466]
**Description:**
Currently, the gRPC service only has the imperative auth support. We need to provide declarative auth support as well.
Design: https://docs.google.com/document/d/1dGw5uUP6kqZNTwMfQ_Ik-k0HTMKhX70XpEA3tys9_kk/edit?usp=sharing

**Comment by MadhukaHarith92** [comment]
Duplicate of https://github.com/ballerina-platform/ballerina-standard-library/issues/1465 ?

**Comment by ldclakmal** [comment]
Nope. Those are different for client and service.

**Comment by dilanSachi** [comment]
Currently the `authDesugar` returns an error when it is `Unauthenticated` or `PermissionDenied`. Here `authDesugar` uses the `caller` to send an error to the client.
For unary instance, the client receives the error in the following manner,

```
helloWorld55Client hClient = check new ("http://localhost:9155");
string|Error result = hClient->hello55UnaryWithCaller(ctxString);
if result is PermissionDeniedError {
    // 
} else {
    //
}
```

For streaming scenario, client receives the error only when trying to receive a response. Is this the expected behaviour?
@daneshk @BuddhiWathsala ?
```
helloWorld55Client hClient = check new ("http://localhost:9155");
Hello55BiDiWithCallerStreamingClient strClient = check hClient->hello55BiDiWithCaller();
check strClient->sendContextString({
    content: "Hello from client",
    headers: requestHeaders
});
check strClient->complete();
string|Error? s = strClient->receiveString();
if s is UnauthenticatedError {
    //
} else {
    //
}
```
