### ISSUE TITLE
HTTP services become unresponsive when the errors are not handled in respond statements

### ISSUE THREAD

**Issue by madushajg** [ballerina-platform/ballerina-standard-library#1509]
**Description:**

I have a simple service like below which hasn't handle the errors in the resond statement.
```ballerina
import ballerina/log;
import ballerina/http;
import ballerina/lang.runtime;

service / on new http:Listener(8090) {
    resource function get path(http:Caller caller, http:Request request) returns error? {

        log:printInfo("info log");
        runtime:sleep(10);
        check caller->respond("Hello");
    }
}

```
This service becomes unresponsive when I make few requests with 4 seconds timeout (which causes the error in respond statment).

Though this is causing due to double responses, it is better to improve this case since users tend to write service like above in general.

**Steps to reproduce:**
1. Run the above service
2. Make few requests (about 10 to 20) with a timeout of less than 10 seconds
3. Try to invoke the service without an explicit timeout (or a timeout higher than 10 seconds)

**Affected Versions:**
SL Beta1

**Comment by chamil321** [comment]
This is not a bug. This is the expected behaviour. Ballerina user should aware of the following when writing services.
- Returning from resource result in a response to the caller
- A request cannot be served with multiple responses(1:1)
- Handle error of `caller->respond()` method
- Use [typed resource responses
](https://ballerina.io/learn/by-example/http-resource-returns)

Also this issue result in a panic behaviour which log an error to console and internal log

**Comment by chamil321** [comment]
However we could reproduce the unresponsiveness locally when sending a subsequent response after the `respond` operation. Ideally the thrown error should not lead to an unresponsive state of the listener.
