### ISSUE TITLE
@ResourceConfig should have caching configuration

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-standard-library#1533]
**Description:**
At the moment the only way to configure cache control for response is by setting those in the http:Response object. But with the new REST API design Response objects are really used. 

On the other side, caching is a common practice in REST for GET request which is considered as safe and idempotent. 

Also, usually caching is another QoS like security which should not get in the way of API logic.

**Comment by shafreenAnfar** [comment]
On second thoughts, I think we can make it part of the below annotation. 

`@http:Payload{mediaType:"application/xml", cacheConfig: myconfig} `

**Comment by chamil321** [comment]
> On second thoughts, I think we can make it part of the below annotation.
> 
> `@http:Payload {cacheConfig: myconfig} `

Did you mean the `ResponseCacheControl` from `cacheConfig`? Because, ResponseCacheControl contains stuff related to response cache directives

**Comment by shafreenAnfar** [comment]
True. 

I thought we could validate it using the compiler plugin. Is there a better alternative ?

**Comment by chamil321** [comment]
@shafreenAnfar We can validate from the compiler plugin. Since field is there, code suggestions will pop up to have it in the inbound payload(databinding) annotation which is not a good experience from the user point of view. 

Suggestions
1. Introduce separate annotation as `ResponseInfo` and use it use with outbound payload(response) and use `Payload` annotation only with inbound payload(databinding). But this is an API change.
```ballerina
returns @http:ResponseInfo{cacheControl: config, mediaType:"text/plain+id"} string {}
```
2. As the initial suggestion, have it in the `ResourceConfig` under the field of `responseCacheControl`
```ballerina
    @http:ResourceConfig {
        responseCacheControl: config
    }
```  
3. Introduce a new annotation as `ResponseInfo` and use it with return types. API addition
```ballerina
returns @http:ResponseInfo{cacheControl: config} @http:Payload {mediaType:"text/plain+id"} string {}
```

**Comment by chamil321** [comment]
As discussed, let's go with the 3rd suggestion of introducing new annotation.

```ballerina
@http:CacheControl {noCache: false}
```
@shafreenAnfar @TharmiganK

**Comment by shafreenAnfar** [comment]
What are the default values for fields in `@http:CacheControl` ?

**Comment by TharmiganK** [comment]
Since the minimum requirement to enable caching is to have `nocache` directive **OR** `max-age=0; must-validate` directives in `cache-control` header **AND** have either one of the validation headers : `etag` or `last-modified`, we can have the following default values in the `@http:CacheConfig` annotation : 
```ballerina
public type HttpCacheConfig record {|
    boolean mustRevalidate = false;
    boolean noCache = true;
    boolean noStore = false;
    boolean noTransform = false;
    boolean isPrivate = false;
    boolean proxyRevalidate = false;
    decimal maxAge = -1;
    decimal sMaxAge = -1;
    string[] noCacheFields = [];
    string[] privateFields = [];
    boolean setETag = true;
    boolean setLastModified = true;
|};
```

**Comment by TharmiganK** [comment]
**This annotation can only support return types of** `anydata` **and** `SucessStatusCodeResponse`.(For other return values cache configuration will not be added through this annotation)

**Comment by chamil321** [comment]
> Since the minimum requirement to enable caching is to have `no-cache` directive **OR** `max-age=0; must-validate` directives in `cache-control` header **AND** have either one of the validation headers : `etag` or `last-modified`, we can have the following default values in the `@http:CacheConfig` annotation :
> 
> ```ballerina
> public type HttpCacheConfig record {|
>     boolean mustRevalidate = false;
>     boolean noCache = true;
>     boolean noStore = false;
>     boolean noTransform = false;
>     boolean isPrivate = false;
>     boolean proxyRevalidate = false;
>     decimal maxAge = -1;
>     decimal sMaxAge = -1;
>     string[] noCacheFields = [];
>     string[] privateFields = [];
>     boolean setETag = true;
>     boolean setLastModified = true;
> |};
> ```

Good Research @TharmiganK
When we set only the `no-cache` in the cache control, the client has to revalidate it for every response IINM. So wouldn't that better if we set `max-age: 600, must-revalidate` in the header? So the response is cached for 10 mins by default and do the revalidation after 10 mins. Also we can make `isPrivate = true;` so that, intermediate proxy caches also can cache the response.
