### ISSUE TITLE
Configuring domain specific media types

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-standard-library#1620]
**Description:**
When designing REST APIs, media types play a key role. They explain the application semantics of the API. When solving a domain specific business problem it is natural to come up with domain specific media types such as `application/vnd.wso2.sales+json`. At the moment it seems there is no way to configure `vnd.wso2.sales` prefix at a single location.

**Comment by TharmiganK** [comment]
**Option 1 :**
We can have this prefix in the Listener configuration, so that all the services attached to this Listener can append this prefix to the content-type header. 

**Option 2 :**
We can have it in the Service configuration, so that all the resources defined inside this service can only append this prefix. 
If we want to have both then prefix configured in service should be prioritize. 

The usability of the prefix in Option 1 is higher than Option 2. And Option 1 is more like a **domain** specific media types whereas Option 2 is like a **service** specific media types. WDYT?

 @shafreenAnfar @chamil321

**Comment by chamil321** [comment]
> **Option 1 :**
> We can have this prefix in the Listener configuration, so that all the services attached to this Listener can append this prefix to the content-type header.
> 
> **Option 2 :**
> We can have it in the Service configuration, so that all the resources defined inside this service can only append this prefix.
> If we want to have both then prefix configured in service should be prioritize.
> 
> The usability of the prefix in Option 1 is higher than Option 2. And Option 1 is more like a **domain** specific media types whereas Option 2 is like a **service** specific media types. WDYT?
> 
> @shafreenAnfar @chamil321

+1 for the option 2. So user has the flexibility to decide depending on their requirement and also feature looks completed. For example, If we implement only the option 1, then after sometime user might request option 2 for some flexibility. 

We can use both listener config(`domainSpecificMediaPrefix`) and service config(`serviceSpecificMediaPrefix`) to keep the configuration. Regardless of how they set the content-type, If these configs are defined by user, every response will contain the prefix in the content type value.

**Comment by shafreenAnfar** [comment]
As discussed the other day, Let's start with **option1** and then if the need comes, let's add it to listener as well.

**Comment by chamil321** [comment]
@shafreenAnfar Should we apply the same logic for the outbound request with payload? ie. Content-type header of the Client requests which does within this service?

**Comment by shafreenAnfar** [comment]
@chamil321 just noticed this. I guess for now, let's leave it as it is.
