### ISSUE TITLE
Compiler plugin test failure in gradle plugin 0.10.2

### ISSUE THREAD

**Issue by dilanSachi** [ballerina-platform/ballerina-standard-library#1655]
**Description:**
gRPC compiler plugin tests are failing in the windows build in ballerina gradle plugin v0.10.2.

**Steps to reproduce:**
Increment the gradle plugin to 0.10.2 from 0.10.0 and build the module in windows.

**Affected Versions:**
Ballerina compiler plugin 0.10.2

**OS, DB, other environment details and versions:**
Windows

**Suggested Labels (optional):**
grpc

**Suggested Assignees (optional):**

**Comment by niveathika** [comment]
Any reason for this bug? AFAIK we don't build compiler test module using this plugin

**Comment by dilanSachi** [comment]
Could not identify a reason yet. All the 13 compiler plugin test cases failed after upgrading ballerina plugin. Decrementing the version fixed the failure.

**Comment by BuddhiWathsala** [comment]
The reason for this issue is as follows.

We cannot enable test groups when we are only building a Ballerina package with tests. Therefore, the following build command won't actually disable LDAP tests. That is the Ballerina behaviour ATM.
```sh
# CMD 01
./gradlew clean build -Pdisable=ldap 
```

To correctly disable LDAP tests, we should do something like:

```sh
# CMD 02
./gradlew clean test -Pdisable=ldap
```

But when we enable `CMD 02`, it won't generate the relevant Ballerina artefacts(i.e balas and jars). We run compiler plugin tests after packing relevant gRPC artefacts(balas and jars). Since we don't have artefacts after executing `CMD 02`, the compiler plugins will definitely fail. Probably the examples and integration tests should also fail. 

Based on that argument, we cannot use `CMD 01` or `CMD 02`. One possible solution is to disable all the compiler plugins tests, examples, and integration tests in Windows. That would solve the issue, but disabling all those is a significant risk.

Here, this PR(https://github.com/ballerina-platform/module-ballerina-grpc/pull/356) introduces another way to handle this case. Here at the Testerina level, we check whether the environment is Windows or not. If it is Windows, we explicitly disable only the LDAP tests. By doing that, the compiler plugin tests, examples, and integration tests are also enabled in Windows.

**Comment by niveathika** [comment]
@BuddhiWathsala Cant, we run "bal build -x test" after the filtered group tests are run?

**Comment by BuddhiWathsala** [comment]
That would work, but adding such a step to the plugin is an additional overhead to the other stdlibs. On the other hand, if we add such a step to the gRPC module, then the gRPC build will deviate from other stdlibs, and in future, it may lead to problems when we upgrade the plugin. 

Anyhow, we have to prevent running LDAP tests in Windows, so it would be convenient to handle this at the gRPC level without changing the existing Gradle builds.
