### ISSUE TITLE
gRPC caller `complete` behaviour after sending an error

### ISSUE THREAD

**Issue by dilanSachi** [ballerina-platform/ballerina-standard-library#1678]
**Description:**
Currently in the unary scenario, if the server sends an error and then do `caller->complete()` in separate multiple instances, the server gets hanged. For a example, create a server that sends an error to the client as follows,
```ballerina
service "HelloWorld" on ep {
  isolated remote function testErr(HelloWorldCaller caller) {
      Error? err = caller->sendError(error Error("error"));
      checkpanic caller->complete();
  }
}
```
and then write around 10 test cases to call the service.
```ballerina
@test:Config {enable:true}
function testErr() {
    T|Error unionResp = helloWorldClient->testErr();
}
```
If `caller->complete()` is not used, there is no issue, but there may be cases where user explicitly `complete()` the call or else, this can be prevented by returning `()` in [caller](https://github.com/ballerina-platform/module-ballerina-grpc/blob/0aaa2a27dad6d3fd39e69979031aed65f4962e22/ballerina/caller.bal#L79).

**Suggested Labels (optional):**
gRPC

**Comment by BuddhiWathsala** [comment]
I'll add more context to this. There are two cases where we have to consider here.
1. Server sends an error in a simple RPC
2. Server sends an error in a streaming RPC

**Case 01 - Server sends an error in a simple RPC**
```ballerina
service "HelloWorld" on ep {
  isolated remote function testErr(HelloWorldCaller caller) {
      Error? err = caller->sendError(error Error("error"));
      checkpanic caller->complete();
  }
}
```
Here, IMO, when a user sends the error, we should close the connection. However, we cannot restrict the user to call `complete` after the `sendError`. Therefore, we should gracefully handle if the `complete` method throws an error during the execution, probably logging it without panicking.

**Case 02 - Server sends an error in a streaming RPC**

Unlike case 01, we cannot immediately close the connection after sending the error because users are allowed to send valid responses even after an error. Here, in the streaming case, after `sendError` we should not close the connection. The connection will be closed after the user called the `complete` method.

@daneshk any input on this?.

**Comment by daneshk** [comment]
@BuddhiWathsala in both cases, we need to close the connection when the user sends an error. Let me explain the rationale for it,

In gRPC, errors are always sent as response trailing headers. they are not considered as another payload message. trailing headers are passed when we close the connection in the last data frame. So we have to close the connection. If the user needs to pass the error message without closing the connection, that has to be part of the response payload message.

+1 to give a warning/error message saying `The connection is already closed`
