### ISSUE TITLE
Compilation error "method is too large" occurs when Parameterized Queries are used

### ISSUE THREAD

**Issue by imsuneth** [ballerina-platform/ballerina-standard-library#1753]
**Description:**
The application has several methods containing Parameterized queries that has around 12 parameters. The compilation fails saying that the "method is too large".
Methods containing Parameterized queries that has around 3 parameters does not give this error.

```
ERROR  method is too large: 'storeIssuesToDB'
error: compilation contains errors
```

**Affected Versions:**
slbeta2

**OS, DB, other environment details and versions:**
windows 10,  mysql-connector-java-8.0.24

**Related Issues:**
https://github.com/ballerina-platform/ballerina-lang/issues/19033

**Workaround I used:**
Wrapped each parameterized query in a separate method and used them.

**Comment by daneshk** [comment]
This is not a standard library-specific issue. This is an issue with the generated JVM byte code and the runtime team is currently looking into this.
Closing this issue since this is duplicated with ballerina-platform/ballerina-lang#19033. Please use ballerina-platform/ballerina-lang#19033 to track the status of the issue.
