### ISSUE TITLE
gRPC server response is not compressed

### ISSUE THREAD

**Issue by tharinduwijewardane** [ballerina-platform/ballerina-standard-library#1899]
**Description:**
Scenario: A large payload (8MB) is sent from a java client to a ballerina server and stored. Then the payload is sent from the ballerina server to a go client. While the client to server transfer with compression is successful, server to client transfer (with compression) is not. Following error is printed at the go client
```
"rpc error: code = ResourceExhausted desc = grpc: received message larger than max (8090038 vs. 4194304)"
```
It seems the server's response is not compressed.
gRPC compression is enabled in the server's response as follows
```
        GetAstResponse response = {
            obsId: req.obsId,
            'version: 'version,
            ast: ast
        };
        map<string|string[]> headers = {};
        headers["grpc-encoding"] = "gzip";
        var res = caller->sendContextGetAstResponse({
            content: response,
            headers: headers
        });
```

**Steps to reproduce:**
1. Setup a ballerina gRPC server to send a large payload when a request is received. Enable compression.
2. Send the request from a client

**Affected Versions:**
Ballerina slbeta2

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by daneshk** [comment]
@dilanSachi Can you check this

**Comment by BuddhiWathsala** [comment]
@tharinduwijewardane I tried this in Ballerina, but couldn’t reproduce. Maybe my message size is small, I'll try with a larger one. 

However, I found this issue occurred at the Golang level [1]. In the meantime, could you please try the solution here [1]?

[1] https://stackoverflow.com/questions/55362342/grpc-received-message-larger-than-max-8653851-vs-4194304

**Comment by tharinduwijewardane** [comment]
@BuddhiWathsala It works when the `MaxCallRecvMsgSize` is set from the go client. But I am not sure whether it gets compressed during the transfer. Here is a large json file [1] of 8.2 MB. When compressed to a zip file it gets reduced to 326 KB.

[1] - https://drive.google.com/file/d/1FBJzfNMCFrGmXKfXsbo5hf7S3gLAgdKb/view?usp=sharing

**Comment by BuddhiWathsala** [comment]
@tharinduwijewardane are you using a streaming gRPC call?

**Comment by tharinduwijewardane** [comment]
> @tharinduwijewardane are you using a streaming gRPC call?

no

**Comment by BuddhiWathsala** [comment]
I hope you represent the AST using gRPC `Struct`. Am I right?

**Comment by BuddhiWathsala** [comment]
> @BuddhiWathsala It works when the `MaxCallRecvMsgSize` is set from the go client. But I am not sure whether it gets compressed during the transfer.
> 
> Here is a large json file [1] of 8.2 MB. When compressed to a zip file it gets reduced to 326 KB.
> 
> [1] - https://drive.google.com/file/d/1FBJzfNMCFrGmXKfXsbo5hf7S3gLAgdKb/view?usp=sharing

@tharinduwijewardane, you aren't sure about the compression because you had to set the `MaxCallRecvMsgSize` value to `8MB`, right?

**Comment by tharinduwijewardane** [comment]
AST is a string.

Yes. Earlier, in the error its mentioned the limit is ~4 MB.

**Comment by BuddhiWathsala** [comment]
We cannot claim based on the `MaxCallRecvMsgSize` because Golang also has a confusing behaviour where we need to specify the message size after decompression[1]. At the Java level also, this is still at the experimental level[2].

Anyhow, we have to verify the server-side compression in Ballerina. Unlike Java, Ballerina client-side compression and server-side compression follow a common path. I'm currently looking into verifying the behaviour.

[1] https://github.com/grpc/grpc-go/issues/4761
[2] https://github.com/grpc/grpc-java/issues/1704

**Comment by BuddhiWathsala** [comment]
We were able to identify the root cause and this issue occurred due to two main sub-problems:
a. Compressing logic has to improve
b. Ballerina server does not know in which cases it should compress the message

The sub-problem (a) is fixed, and we have to clarify a design for (b). Therefore, we did background work on how other languages handle this use case, and the summary is as follows:

### Go 
|Experiment|Client|Server|Request|Response|Status|
|---|---|---|---|---|---|
|1|Gzip disabled|Gzip disabled|Not compressed|Not compressed|Successful|
|2|Gzip enabled|Gzip disabled|Compressed|N/A|Error|
|3|Gzip disabled|Gzip enabled|Not compressed|Not compressed|Successful|
|4|Gzip enabled|Gzip enabled|Compressed|Compressed|Successful|

The error message of 2nd experiment:
```sh
2021/09/17 17:10:14 could not greet: rpc error: code = Unimplemented desc = grpc: Decompressor is not installed for grpc-encoding "gzip"
```

### Java

|Experiment|Client|Server|Request|Response|Status|
|---|---|---|---|---|---|
|1|Gzip disabled|Gzip disabled|Not compressed|Not compressed|Successful|
|2|Gzip enabled|Gzip disabled|Compressed|Not compressed|Successful|
|3|Gzip disabled|Gzip enabled|Not compressed|Compressed|Successful|
|4|Gzip enabled|Gzip enabled|Compressed|Compressed|Successful|

Note that, the Java client always sends the `grpc-accept-encoding=gzip` header even though we enabled Gzip or not. That is why in experiment 03, the response is compressed. It did not happen in Go.

We can implement similar behaviour in Ballerina. @daneshk @shafreenAnfar @dilanSachi WDYT?

**Comment by daneshk** [comment]
This is a great analysis. Thanks, @BuddhiWathsala for checking other languages. 

We can implement as Java does. sending `grpc-accept-encoding` from the client is the right way. It says the server, which encoding client support. when we do compression on the server-side. we can check and decide whether to compress or not.

**Comment by BuddhiWathsala** [comment]
Ballerina gRPC compression proposal https://github.com/ballerina-platform/ballerina-standard-library/issues/1952
