### ISSUE TITLE
CodeAction compiler Test failure

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-standard-library#2304]
**Description:**
```
> Task :http-compiler-plugin-tests:test

Gradle suite > Gradle test > io.ballerina.stdlib.http.compiler.codeaction.ChangeHeaderParamTypeTest > testCodeActions[0](service.bal, 20, 49, io.ballerina.projects.plugins.codeaction.CodeActionInfo@39540d57, result1.bal) FAILED
    io.ballerina.projects.ProjectException at ChangeHeaderParamTypeTest.java:47

Gradle suite > Gradle test > io.ballerina.stdlib.http.compiler.codeaction.ChangeHeaderParamTypeTest > testCodeActions[1](service.bal, 20, 49, io.ballerina.projects.plugins.codeaction.CodeActionInfo@58139a43, result2.bal) FAILED
    io.ballerina.projects.ProjectException at ChangeHeaderParamTypeTest.java:47

Gradle suite > Gradle test > io.ballerina.stdlib.http.compiler.codeaction.ChangeReturnTypeWithCallerTest > testCodeActions[0](service.bal, 24, 65, io.ballerina.projects.plugins.codeaction.CodeActionInfo@7d22ad86, result1.bal) FAILED
    io.ballerina.projects.ProjectException at ChangeReturnTypeWithCallerTest.java:47
```

First issue is with the distribution path. I changed it to 
```java
    private static final Path DISTRIBUTION_PATH = Paths.get("../", "target", "ballerina-runtime")
            .toAbsolutePath();
```
and made a progress. Then getting `Expect atleast 1 code action` as code actions are 0

<img width="1171" alt="Screenshot 2021-10-29 at 19 41 00" src="https://user-images.githubusercontent.com/8381003/139450634-6559dfca-3732-4819-a74a-6691ec7a4099.png">

Disabled tests as this is a blocker for the package.
[logs_6337.zip](https://github.com/ballerina-platform/ballerina-standard-library/files/7442706/logs_6337.zip)

**Comment by IMS94** [comment]
@chamil321 I had a look at this. This is caused by https://github.com/ballerina-platform/module-ballerina-http/pull/698  which has been done under https://github.com/ballerina-platform/ballerina-standard-library/issues/2134.

With this, now the compiler plugin do not run plugin validations if the source already has errors. This has caused the diagnostics required by the code actions to not be published. Since this is intended, I will change the code action tests to match.
