### ISSUE TITLE
`http:parseHeader` method is not designed to parse the Link header

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-standard-library#2403]
Here is the link header value: `<https://api.github.com/repositories/73930305/stargazers?page=2>; rel="next", <https://api.github.com/repositories/73930305/stargazers?page=98>; rel="last"`

Signature of the p`arseHeader` function: 
```
public isolated function parseHeader(string headerValue) returns [string, map<any>]|ClientError 
```

When parsing the above link header using the `parseHeader` function, I get only the first URL and its map.

**Comment by sameerajayasoma** [comment]
Looks like there is another issue with this function. 

```
io:println(header);
io:println(check http:parseHeader(header));
```

```
<https://api.github.com/repositories/73930305/stargazers?page=2>; rel="next", <https://api.github.com/repositories/73930305/stargazers?page=98>; rel="last"
["<https://api.github.com/repositories/73930305/stargazers?page=2>",{"rel":""next""}]
```

Look at the returned map value. The value of the key `"rel"` is `""next""`. It should be `"next"`

**Comment by chamil321** [comment]
The method is revamped as follows:
1. Introduce `HeaderValue` record
```ballerina
# Represents the parsed header value details
public type HeaderValue record {|
    # The header value
    string value;
    # Map of header parameters
    map<string> params;
|};
```

2. Return an array of `HeaderValue` records which could accommodate multiple header values and parameters

```ballerina
http:HeaderValue[] values = check http:parseHeader("text/plain;level=1;q=0.6, application/xml;level=2");
```

3. The second comment describe a situation where the header param value has become a string with quations. Since there can be many types such as int, booleans, we should not special case it to remove the quotations

Eg: `text/plain;level=1;q=0.6`, `<https://api.github.com>; rel="next"`
