### ISSUE TITLE
Fix FTP 2.0.1 release failure

### ISSUE THREAD

**Issue by Maninda** [ballerina-platform/ballerina-standard-library#2425]
$subject

**Comment by Maninda** [comment]
Manually released.

**Comment by niveathika** [comment]
The original issue was that Ballerina.toml files were not committed and pushed during the release, Mainly because testcases are not running in release build, Shall we fix this in this effort?

https://github.com/ballerina-platform/module-ballerina-ftp/blob/release-2.0.1/build.gradle#L100

https://github.com/ballerina-platform/module-ballerina-oauth2/blob/master/build.gradle#L94

**Comment by Maninda** [comment]
> The original issue was that Ballerina.toml files were not committed and pushed during the release, Mainly because testcases are not running in release build, Shall we fix this in this effort?
> 
> https://github.com/ballerina-platform/module-ballerina-ftp/blob/release-2.0.1/build.gradle#L100
> 
> https://github.com/ballerina-platform/module-ballerina-oauth2/blob/master/build.gradle#L94

Fixed in https://github.com/ballerina-platform/module-ballerina-ftp/pull/459
