### ISSUE TITLE
Should a resource with POST action respond with 201 Created by default?

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-standard-library#2469]
The following resource responds with 200 OK at the moment. 

```ballerina
    resource function post albums(@http:Payload Album album) returns Album {
        ....
    }
```

Should it respond with 201 instead? Post is used to create or append new resources. In that case, responding with 201 make sense to me.

**Comment by shafreenAnfar** [comment]
Yeah, the given suggestion does align with the semantics we follow. I think we can stick to the below table. `PUT` could result in creating a resource or updating an existing one. Since the most common use-case is to update. We can stick to 200 OK.

Verb | Semantics | Status Code
-- | -- | --
GET | Lets you retrieve a resource representation. GET requests are always safe and subject to caching. Since it is safe it is idempotent as well | 200 OK
POST | Lets you create a new resource or append a new resource to a collection of resources | 201 Created
PUT | Lets you create a new resource or update an existing resource | 200 OK
PATCH | Lets you partially update an existing resource whereas PUT update the entire resource | 200 OK
DELETE | Lets you delete a resource | 200 OK
