### ISSUE TITLE
Data mapping for `application/www-x-form-urlencoded`

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-standard-library#2526]
At the moment we do the data mapping as in https://github.com/ballerina-platform/ballerina-standard-library/issues/976. But we have missed the below data mapping.

Type | Media Type
-- | --
map\<string\> | application/www-x-form-urlencoded

**Comment by shafreenAnfar** [comment]
I think this a blocker for the release because we have missed a common content-type.

**Comment by chamil321** [comment]
@ayeshLK Let's add the map type support for the service binding first. Then gradually introduce it to the client. When introducing `map<string>` if the content type of the annotation is `@http:Payload{mediaType : "application/www-x-form-urlencoded"}` , get the payload as string and create map. Otherwise, get the payload as json

**Comment by shafreenAnfar** [comment]
Here is the proposal https://github.com/ballerina-platform/ballerina-standard-library/issues/2530
