### ISSUE TITLE
Conflicting jars warning when using mysql module

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-standard-library#2602]
**Description:**
When using the `ballerinax/mysql` and `ballerina/sql` in the same project, following warning is printed:

```ballerina
warning: Detected conflicting jar files:
                'sql-native-1.3.0-20220119-175600-391fb68.jar' dependency of 'ballerina/sql' conflict with 'sql-native-1.2.0.jar' dependency of 'ballerinax/mysql'
```

**Steps to reproduce:**
Create a ballerina project and do something like below:
```
import ballerina/sql;
import ballerinax/mysql;

mysql:Client mysqlClient = check new (mysqlHost, user = mysqlUser, password = mysqlPassword, database = mysqlDatabase);
sql:ExecutionResult|sql:Error result = mysqlClient->execute(`insert into products (product_name, price, currency) values (${product.productName}, ${product.price}, ${product.currency})`);
```

**Affected Versions:**
Ballerina 2201 RC1

**Comment by niveathika** [comment]
It seems you have tested this with prod central. This is the expected behavior due to,
1. The RC pack still contains the sql timestamped versioned jar.
2. The latest `mysql` module is not published yet. The sample is pulling the beta6 distribution dependent mysql module.

This warning will resolve itself once the GA release goes live.
