### ISSUE TITLE
Proposal:  Subscription Support in Ballerina GraphQL Package

### ISSUE THREAD

**Issue by Nuvindu** [ballerina-platform/ballerina-standard-library#2821]
## Summary
GraphQL Subscription is one of the three operations in GraphQL. However, the Ballerina GraphQL package only supports query and mutation. This proposal is to introduce subscription support for the Ballerina GraphQL package.
## Goals
* Provide GraphQL subscription support for Ballerina GraphQL services.
## Non-Goals
* Add a Pub/Sub module to the Ballerina GraphQL package to provide APIs for the users to simplify their code.
## Motivation
GraphQL subscriptions are widely used in real-time applications. Using subscriptions, GraphQL servers can send data continuously to the clients while maintaining a persistent connection. However, at the moment such applications cannot be developed using the Ballerina GraphQL package as it only supports `query` and `mutation` operations. Hence, there is a need to support `subscription` operations also. 

On the other hand, the Ballerina GraphQL package is not spec-compliant until the `subscription` operation is supported.

### Overview
There are a few challenges in implementing a `subscription` operation. First, there should be a way to clearly distinguish `subscription` resolvers from `mutation` and `query` operations. So that the GraphQL package can generate the schema from the code. 

Second, unlike `mutation` and `query` operations, the `subscription` operation requires a persistent connection. Unbounded events are continuously pushed to the client using the persistent connection. The same event might be pushed across multiple persistent connections.

The proposed solution addresses all the above while minimizing the code that has to be written to provide a better user experience.
#### Subscription Resolver

Subscription resolvers use resource functions with the `get` accessor. This is because subscription resolvers don’t mutate the application state. The return value of the subscription resolver is the Ballerina stream. The stream can be any type.

The returned stream is mapped to one or more connections. Since the connection must be persistent, HTTP connections are upgraded to WebSocket connections. Underline implementation reads the stream in a loop and pushes the data to mapped WebSocket connections until the end of the stream or an error is returned.

The following is an example resolver for graphql subscription.

```ballerina 
 resource function get message() returns stream<string,error?> { ... }
```

Both `query` operation and `subscription` use resource functions to represent them. Unlike `query` operations, `subscription` operations only allow returning streams. This allows the GraphQL engine to distinguish one from the other.
### Writing a GraphQL Subscription Service

Writing a GraphQL service with subscriptions must not be complicated from the developer’s perspective. Following is how the GraphQL subscription service can be written.
#### Initiate a Pipe Instance in the GraphQL Service

An array of [Pipes](#pipe) has to be instantiated first. These pipes can be used to produce and consume messages. A detailed explanation of the Pipe can be found later. This array will hold a separate pipe for each subscribed client.

```ballerina
  service /graphql on new graphql:Listener(4000) {
     Pipe[] pipes;
     ...
  }
  ``` 
#### Subscription Resolver

As mentioned earlier the subscription resolver must return a stream. An instance of the return stream can be created with the help of the Pipe. Therefore a new pipe instance must be instantiated here and added that to the pipes array. Then a stream must be returned using the `consumeStream` method of the pipe. To do this, the Pipe uses Ballerina’s dependent type feature. 

```ballerina 
 resource function get message() returns stream<string,error?> {
      Pipe pipe = new(10);
      pipes.push(pipe);
      return pipe.consumeStream();  
 }
```

#### Triggering Events

The event source of subscriptions could be anything, in this case, the event source is the `addMessage` mutation resolver. Once the message is received from the event source, the message can be produced to each pipe in the pipe array. The produced message can be consumed from the pipe using the `consumeStream` method.

 
```ballerina
 remote function addMessage(string msg) {
    for pipe in pipes {
      pipe.produce(msg, timeout = 10);
    }
    ...
 }
```
 

### Pipe
The Pipe allows you to send data from one place to another. Following are the APIs of the Pipe. There is one method to produce and two methods to consume. Users can use either option as they wish but not both at once. The implementation of the `consumeStream` usually uses the `consume` method to provide its functionality.

```ballerina 
    public class Pipe {

        public function init(int 'limit) { ...//sets a limit }
        
        // produces data into the pipe
        // if full, blocks
        public isolated function produce(any data, decimal timeout) = external;
    
        // returns data in the pipe
        // if empty, blocks
        public isolated function consume(decimal timeout, typedesc<any> t = <>) returns t|error = external;
    
        // returns a stream 
        // data produced to the pipe can be fetched by the stream
        public isolated function consumeStream(decimal timeout, typedesc<any> t|error = <>) returns stream<t, error?> = external;
    
    }
```

The pipe can hold up to n number of data. In case the pipe is full, the `producer` method blocks until there is a free slot to produce data. On the other hand, in case the pipe is empty, the `consumer` method blocks until there is some data to consume. This behavior is somewhat similar to `go channels`. A timeout must be set to the `produce` and `consume` methods to regulate the waiting time in the blocking state.

### Filtering Events

Subscription resolvers can be designed to filter data according to the input parameters as shown below.
#### Custom Generator

The user has to create a new generator function to filter data from the stream.  And it can be configured any way the user prefers.

 
```ballerina
  class CustomGenerator {
    private stream<Person, error?> originalStream;
    private any data;
    function init(stream<Person, error?> originalStream, any data) {
        self.originalStream = originalStream;
        self.data = data;
    }
    public isolated function next() returns record {| Person value; |}|error? {
        MsgRecord|error? msgRecord = self.originalStream.next();
        if msgRecord is MsgRecord {
            Person person = msgRecord.value;
            if(self.data == person.getAge()){
                return { value: person };
            }
        }
        return;
    }
  }
 
  type MsgRecord record {|
    Person value;
  |};
 ```

#### Subscription Resolver

A new custom generator instance has to be created here using the original stream and the input data. Then a new stream must be created using that custom generator. It must be returned after that. 

 
```ballerina
  resource function get personDetails(int age) returns stream<Person,error?>{
      Pipe pipe = new(10);
      pipes.push(pipe);   
      stream<Person, error?> originalStream = pipe.consumeStream();
      CustomGenerator customGenerator = new(originalStream, age);
      stream<Person, error?> filteredStream = new(customGenerator);
      return filteredStream;
  }
```

**Comment by ThisaruGuruge** [comment]
@jclark @sameerajayasoma @sanjiva Can you please provide feedback on this?

**Comment by sanjiva** [comment]
I'm finding it a bit hard to see what the client side will be vs. what the server side will be. Can you put up a sample please?

**Comment by jclark** [comment]
The Pipe aspect of this does not look good to me.  It is not at all specific to GraphQL and needs to be handled in a way that makes available across the platform.

1. Pipe is trying to solve https://github.com/ballerina-platform/ballerina-spec/issues/747. This really needs to be a language feature so it can `Pipe<T>`, rather than using the dependent type feature. Th
2. As regards how Pipe is used in GraphQL, the user shouldn't need to manage an array of pipes. This is not going to interact well with `isolated`. Can you make this work by having the resolver pass in the Pipe to the resource method?
3. Why are you using `get` rather than `subscribe` as the resource method? I would make this a separate method, and functions using this method have to have a Pipe argument.

**Comment by jclark** [comment]
We also need to ensure gRPC and GraphQL are handling subscriptions in a consistent way. As far as I remember, gRPC is doing this without a Pipe concept.  Why can you not do this just with streams?

**Comment by ThisaruGuruge** [comment]
> I'm finding it a bit hard to see what the client side will be vs. what the server side will be. Can you put up a sample please?

Hi @sanjiva,

Following is a complete code example for the server implementation:

```ballerina
import ballerina/graphql;

service /graphql on new graphql:Listener(4000) {
    // Define a Pipe array to hold pipe objects of clients.
    // Pipe is defined inside the GraphQL package temporarily,
    // since Ballerina do not have a Pipe implementation currently.
    private graphql:Pipe[] pipes; 

    function init() {
        self.pipes = [];
    }

    // Remote function to publish messages
    remote function addMessage(string msg) returns string {
        foreach pipe:Pipe pipe in self.pipes {
            error? produce = pipe.produce(self.message, timeout = 10);
        }
        return self.message;
    }

    // resource function as a subscription resolver
    resource function get messages() returns stream<string, error?> {
        
        //instantiate a new pipe for the client
        pipe:Pipe pipe = new(10);
        
        // add the pipe into the pipe array
        self.pipes.push(pipe);
        
        // data will be returned from the stream when a new message is added to the pipe
        return pipe.consumeStream(timeout = 10);
    }
}
```

The Ballerina GraphQL package does not have a client implementation yet. (Client implementation is in progress and it still does not support subscription operations, it's in the future plans). Once implemented, the client code would be similar to the other streaming client implementations in Ballerina (i.e.: gRPC). The client code would look something like this:

```ballerina
import ballerina/graphql;

public function main() returns error? {
    graphql:Client graphqlClient = check new ("ws://snowtooth.moonhighway.com/graphql");
    string query = "subscription { messages }";
    stream<string, error?> messageStream = check graphqlClient->executeWithType();

    // Process result
}
```

**Comment by shafreenAnfar** [comment]
> The Pipe aspect of this does not look good to me. It is not at all specific to GraphQL and needs to be handled in a way that makes available across the platform.

Yes, it is not GraphQL specific. Initially we thought of having another library for this and then decided against it to keep things simple.

> 1. Pipe is trying to solve https://github.com/ballerina-platform/ballerina-spec/issues/747. This really needs to be a language feature so it can Pipe<T>, rather than using the dependent type feature. 

Yes, `Pipe<T>` would be ideal.

> 2. As regards how Pipe is used in GraphQL, the user shouldn't need to manage an array of pipes. This is not going to interact well with isolated. Can you make this work by having the resolver pass in the Pipe to the resource method?

Yes, we can pass the pipe. However, even if we do so, we may have to store it in a service level variable in order to produce data when there is an event. 

The other option would be to do the following.

1. Make the Pipe class isolated. 
2. Provide a simple Pubsub abstraction on top of the Pipe. So that users can simply `publish` and `subscribe`. Pubsub will internally manage the array of pipe.

```ballerina
import ballerina/graphql;

service /graphql on new graphql:Listener(4000) {
    private graphql:Pubsub pubsub; 

    function init() {
        self.pubsub = new;
    }

    // Remote function to publish messages
    remote function addMessage(string msg) returns string {
        self.pubsub.publish(msg);
        return self.message;
    }

    // resource function as a subscription resolver
    resource function get messages() returns stream<string, error?> {
        return self.pubsub.subscribe();
    }
}
``` 
**Note**: We need to think through the details of Pubsub. However, the above is the basic idea. We were planning to do this as the second step of the implementation.

> 3. Why are you using get rather than subscribe as the resource method? I would make this a separate method, and functions using this method have to have a Pipe argument.

We were thinking in terms of read/write, mutation is write whereas query and subscription are read. The difference is how you read data, in one case it is a single message and in the other case it is a stream of messages. Hence, we thought of using get while returning a stream.

**Comment by jclark** [comment]
> Both in gRPC and GraphQL we return a stream. But in the case of unbounded streams gRPC uses the caller to stream messages to the client

I still don't understand why  you need Pipe/PubSub for GraphQL but not gRPC.

> 2. Provide a simple Pubsub abstraction on top of the Pipe. So that users can simply `publish` and `subscribe`. Pubsub will internally manage the array of pipe.

That looks much better, but I think that `pubsub` should be a module-level variable not a field of the service object. It's crucial that there is exactly one of them. In general, there will be multiple services involved, some which trigger events and some which consume them.  The `pubsub` mechanism is a way of coordinating these services.

```
// pubsub:Channel is an isolated class
// but the values also has to be final
final pubsub:Channel demoChannel = new;

service /graphql on new graphql:Listener(4000) {
    // resource function as a subscription resolver
    // should completion type be `error` or `error?`
    resource function sub messages() returns stream<string, error?> {
        // hopefully dependent type feature can avoid a cast here
        return demoChannel.subscribe();
    }
}

service / on new http:Listener(8080) {
    resource function post addMessage(string msg) returns string {
        demoChannel.publish(msg);
        return msg;
    }
}
```

The really tricky aspect of this is how to make graceful shutdown work. Note that the graphql resource function may be using a query to filter streams.  When the shutdown happens, it may be in the middle of generating the next member of the stream. Graceful shutdown should

- wait for any addMessage functions to complete
- close the channel, which will tell the streams subscribed to the channel that there are no more events coming
- it then needs to schedule each strand that was handling a stream subscription so that it can deal with the end of stream (which may be an error or `()` depending on how we set things up)

The module needs to know that the http service publishes into the demoChannel, so it can let the http service finish before it closes the channel. But with this scheme of things it doesn't know that: it's too low-level.

Overall I would say the pubsub functionality is a fundamental language primitive for inter-strand communication. I don't think it's going to work out well to do this as part of graphql.

**Comment by jclark** [comment]
I suggest we continue pubsub discussion here https://github.com/ballerina-platform/ballerina-spec/issues/747

**Comment by shafreenAnfar** [comment]
We have decided only to implement the resolver part of this proposal as the first step.

**Comment by ThisaruGuruge** [comment]
Closing as this is now implemented.
