### ISSUE TITLE
Support @deprecated Directive for Output Object Defined using Record Types

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-standard-library#2998]
**Description:**
The `@deprecated` directive is one of the [default directives defined in the GraphQL spec](https://spec.graphql.org/October2021/#sec--deprecated). 

The `@deprecate` directive is supported through https://github.com/ballerina-platform/module-ballerina-graphql/pull/772, but it does not support `INPUT_OBJECT` types due to  https://github.com/ballerina-platform/ballerina-spec/issues/823. Once this issue is fixed, `INPUT_OBJECT`s should be allowed to mark their fields as deprecated using the `@deprecated` directive.

**Comment by ThisaruGuruge** [comment]
We can implement this now since the lang supports @deprecated annotation on record fields now.

**Comment by DimuthuMadushan** [comment]
As per the GraphQL [spec](https://spec.graphql.org/October2021/#sec--deprecated), the `@deprecated` annotation can not be applied to the `Input Object` fields. Since we use the ballerina records type as input objects, developer able to define deprecate annotation for record fields. Therefore a warning will be added to the GraphQL package. However, for the Output objects(define using record types), this annotation will be supported.
