### ISSUE TITLE
`http` request for an `https` endpoint fails with a wrong error message

### ISSUE THREAD

**Issue by TharmiganK** [ballerina-platform/ballerina-standard-library#3034]
**Description:**

When we make a request call from a `http` client (without secure socket config) to a `https` endpoint, the request fails with the following error :
`Remote host closed the connection before initiating inbound response`

This error message is not related to the scenario, there should be an error thrown from SSL handshake level.

**Steps to reproduce:**

```ballerina
import ballerina/http;
import ballerina/test;

http:Client clientEP = check new("http://localhost:9090");

listener http:Listener serverEP = check new(9090, {
    secureSocket: {
        key: {
            path: "certsandkeys/ballerinaKeystore.p12",
            password: "ballerina"
        }
    }
});

service on serverEP {
    resource function post echo(@http:Payload string payload) returns string {
        return payload;
    }
}

@test:Config{}
function test() returns error? {
    http:Response _ = check clientEP->post("/echo", "hello");
}
```

```console
bal test sample.bal
```

```console
Compiling source
        test.bal

Running Tests

        test.bal

                [fail] test:

                    Remote host closed the connection before initiating inbound response


                0 passing
                1 failing
                0 skipped

error: there are test failures
```

**Affected Versions:**
Ballerina SwanLake 2201.1.0

**Comment by Bhashinee** [comment]
Analyzed the scenario and these are the findings. 
The client is an HTTP(non-secure) client where it is not aware of the SSL. So what the client does is, once the TCP connection is established, it starts writing the request to the backend. On the server side, being an HTTPS server, it waits for the SSL handshake messages. Instead, the server gets an HTTP request. So from the server side, it closes the connection.

The only notification we get from the client side is a `channel Inactive` event. It doesn't contain a message related to SSL. Since the client is not aware of the SSL connection and the server is also not sending any details about the SSL failure, there is no way of giving that information out.
