### ISSUE TITLE
Date format issue when converting string to UTC or Civil

### ISSUE THREAD

**Issue by nadeesha5814** [ballerina-platform/ballerina-standard-library#3244]
**Description:**
utcFromString or civilFromString throws an error when the month or day format is not 2 digits. So for example when you set the month to 8 (instead of 08) or date to 4 ( instead of 04) it throws an error as below. 

`Provided '2022-8-4T10:15:30.120Z' is not adhere to the expected format '2007-12-03T10:15:30.00Z'`

This behaviour in inconsistent with another date function civilFromDate.month which returns the month in single digit (8 instead of 08).

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by sahanHe** [comment]
Hi @nadeesha5814 ,

When using `time:civilFromString()` or `time:utcFromString()` APIs, the input `string` should align with RFC 3339 standards which is a profile of ISO8601, where two digits should be used to represent both Date and Month. This is validated in the APIs and if the input doesn't align with the required standard, it returns the above mentioned error.  You can refer the following [chapter](https://www.rfc-editor.org/rfc/rfc3339#section-5:~:text=saving%20rule%0A%20%20%20%20%20%20settings.-,5,-.%20Date%20and%20Time) of the RFC-3339 documentation for a detailed description.

As for the second case, I'm not clear about what `civilFromDate.month` function you mentioned is, but assuming you have used the following code snippet, `civilFromDate` is a `time:Civil` record and in this record, date and month is stored as `int` type. Since the  stored `int` value is directly accessed, it will return a single or double digit integer for both `month` and `date` without any leading zeros.  you can refer the [API doc](https://lib.ballerina.io/ballerina/time/2.2.2/records/Civil) for a detailed description of `time:Civil`.

```ballerina
time:Civil civilFromDate = check time:civilFromString("2016-06-01T14:41:36-08:00");
io:println(civilFromDate.month);
```

To get expected two digit value for the month, `time:civilToString()` can be used with `regex:split()`  as in the second code snippet below.

```ballerina
time:Civil civilTime = check time:civilFromString("2016-06-01T14:41:36-08:00");
string[] timeArray = regex:split(check time:civilToString(civilTime), "-");
io:println(timeArray[1]);
```

**Comment by sahanHe** [comment]
Closing this issue as resolved. Please reopen if there are any related questions.
