### ISSUE TITLE
SQL query doesn't return an error when mandatory fields are not fetched from the database

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-standard-library#3251]
Below code prints out a record even if it doesn't have dateTime.

```ballerina
type Package record {
    int? packageID = ();
    int dateTime;
};
```

```ballerina
stream<Package, error?> resultStream = dbClient->query(`SELECT PACKAGEID, XYZ FROM PACKAGE WHERE PACKAGEID=${packageId};`);
check from Package p in resultStream do {
    // io:println(p.dateTime);
    io:println(p);
;
```

**Comment by niveathika** [comment]
@manuranga What is the sql module version you are using?

**Comment by manuranga** [comment]
I think it's `"1.3.1"` but I am not sure since it was in a different laptop.

**Comment by niveathika** [comment]
From my initial debugging, this is an error in SQL module, we will fix this. 

@kaneeldias This behaviour is due to this piece of code, https://github.com/ballerina-platform/module-ballerina-sql/blob/master/native/src/main/java/io/ballerina/stdlib/sql/nativeimpl/QueryProcessor.java#L285

Here, we are creating an empty record and updating the values. The above use case is not identified in this case. We have to create the record with the processed results.
