### ISSUE TITLE
Make GraphQL services Federation friendly

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-standard-library#3268]
When you do large deployments, it is common to build a bunch of subgraphs and merge them into one supergraph. This is mostly done based on Apollo Federation specification. GW can connect to these subgraphs and resolve the query. 

It would be great if Ballerina can provide a way to implement these subgraphs without any hassle. 

https://www.apollographql.com/docs/federation/federation-spec/

**Comment by MohamedSabthar** [comment]
Proposal :[#3504](https://github.com/ballerina-platform/ballerina-standard-library/issues/3504)

**Comment by anupama-pathirage** [comment]
Since this is done in the board https://github.com/ballerina-platform/ballerina-standard-library/projects/137 can we close the issue. Please create a new issue or update the title/description accordingly if there are remaining parts.

@shafreenAnfar / @MohamedSabthar

**Comment by MohamedSabthar** [comment]
This is closed since the proposal is done, reopening to track the implementation progress.

**Comment by MohamedSabthar** [comment]
The following tasks are to be completed 

- [ ] Implement subgraph configuration in the ServiceConfig annotation.
- [ ] Introduce support for the @key directive through the utilization of the @Entity annotation.
- [ ] Extend the federation types in the schema and test through introspection.
- [ ] Permit the use of the `_Any` type in the field_visitor, ensuring the type is represented as a JSON object with a `__typename` field, and add tests accordingly.
- [ ] Modify the compiler plugin to include a resolver for the `_entities` field.
- [ ] Ensure that compilation errors are returned for any attempts to define `_Any`, `_Entity`, `_Service`, and other federated types, and add tests to validate this.
- [ ] Ensure that compilation errors are returned if `_service` or `_entities` is used as remote or resource names, and add tests to validate this.
- [ ] Implement subgraph schema SDL generation.
- [ ] Modify the compiler plugin to include a resolver for the `_service`.
- [ ] Add tests to validate entities without reference resolvers (i.e. querying the `_entities` field for a non-resolvable entity and verifying that the SDL indicates that the entity returns `resolvable: false`).
- [ ] Collect entities that are not returned by the resolvers (i.e. loop through the types and service classes with the @Entity annotation and validate them recursively since they are the return type of entities resolvers. Create object types for these types and add them to the GraphQL schema).
- [ ] Validate the resolve reference method to ensure it is not returning the incorrect type (this can not be performed at compile time).
- [ ] Test the implementation with GraphQL Apollo Gateway.
- [ ] Add a specification.

**Comment by ThisaruGuruge** [comment]
Closing the issue since this is now implemented.
