### ISSUE TITLE
Inferred dependent type of `http:Response?` not accepted by the HTTP client remote methods

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-standard-library#3290]
Consider the following example:
```ballerina
import ballerina/http;

service on new http:Listener(9090) {
    
    resource function get hi (http:Caller caller) {
        http:Client ep = checkpanic new ("http://localhost:8080");
        http:Response? resp = checkpanic ep->get("/greet"); // this line errors
        http:ListenerError? result = caller->respond(<http:Response>resp);
    }
}

service on new http:Listener(8080) {
    
    resource function get greet () returns json {
        return <json>{"greeting": "Hello World!"};
    }
}
```
Getting the following error when running the above.
```
error: invalid target type, expected: http:Response, anydata or a union of such a type with nil
	at ballerina.http.2:jsonPayloadBuilder(http_client_payload_builder.bal:157)
	   ballerina.http.2:performDataBinding(http_client_payload_builder.bal:41)
	   ballerina.http.2:processResponse(http_client_endpoint.bal:677)
	   ballerina.http.2.Client:processGet(http_client_endpoint.bal:194)
```
Judging by the error message, shouldn't `http:Response` be allowed? Or does this error message mean union of an anydata type with nil?

Note that the above works when I change it as follows:
```ballerina
 http:Response? resp = checkpanic ep->get("/greet", targetType = http:Response);
```

**Comment by MadhukaHarith92** [comment]
This is the expected behavior. The target type cannot be `http:Response?`. The following

```ballerina
 http:Response? resp = checkpanic ep->get("/greet", targetType = http:Response);
```

works because here, the target type is `http:Response` as per the client function definition[[1]](https://github.com/ballerina-platform/module-ballerina-http/blob/8085a717616c51cac7f4a826beb58f2cfd2eae7e/ballerina/http_client_endpoint.bal#L261).

Also, note that the new error is the following in Swan Lake Update 4.
```
error: client method invocation failed: invalid payload target type
cause: invalid payload target type
	at ballerina.http.2:processResponse(http_client_endpoint.bal:650)
	   ballerina.http.2.Client:processGet(http_client_endpoint.bal:286)
```

[1] https://github.com/ballerina-platform/module-ballerina-http/blob/8085a717616c51cac7f4a826beb58f2cfd2eae7e/ballerina/http_client_endpoint.bal#L261

**Comment by pubudu91** [comment]
Ack. But why not rephrase the old error message though? With the new error message, the user is left with no clue about how to rectify his mistake.
