### ISSUE TITLE
error: {ballerina/http}SslError message=Keystore password must be provided for secure connection

### ISSUE THREAD

**Issue by starsmall-xiaoqq** [ballerina-platform/ballerina-standard-library#338]
**Description:**

I deployed the "user_retrieval_service" program (https://ballerina.io/learn/deploying-ballerina-programs-in-the-cloud/.) into  EKS . The program can not be normally started. And the pod logs message is showing : error: {ballerina/http}SslError message=Keystore password must be provided for secure connection.

**Steps to reproduce:**

I can run the program locally in windows10 with "ballerina run" command. The problem was only occurred in kubernetes (EKS). 

1. run "ballerina.bat build .\user_retrieval_service.bal"  with security/ballerinaKeystore.p12 and service-config.toml in place. The docker images is pushed to registry.
 
2. I check the generated kubernetes/user_retrieval_service.yaml file, the mountPath separator for keystore file seems incorrectly: 
  volumeMounts:
        - mountPath: "\\home\\ballerina\\.\\security"
          name: "userretrievalep-keystore-volume"
          readOnly: true
        - mountPath: "/home/ballerina/conf/"
          name: "userretrievalservice-ballerina-conf-config-map-volume"
          readOnly: false

3. I change the  "\\home\\ballerina\\.\\security" manually to  "/home/ballerina/security/"

4.  run "kubectl apply -f   .\kubernetes\" .
   The docker image is correctly downloaded, but it can not be started (the error message is shown as the title).

**Affected Versions:**
I use Ballierina 1.2.4  

**OS, DB, other environment details and versions:**
build environment:  windows 10
kubernetes: 1.14

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by ldclakmal** [comment]
@starsmall-xiaoqq Thanks for reporting the issue. I suspect this issue is due to no configuring the `copyFiles` config at `@kubernetes:Deployment{}` annotation [1].

This issue is no longer there with Ballerina Swan Lake Beta1 release. I tried a similar scenario where a HTTP service is secured with SSL/TLS  and deployed it on Kubernetes. You can refer to [2] [3] guides for more information. The scenario I've tried can be found at [4].

Feel free to reopen if the problem still exists.

[1] https://ballerina.io/1.2/learn/deployment/kubernetes/#supported-kubernetes-annotations
[2] https://ballerina.io/learn/user-guide/deployment/code-to-cloud/
[3] https://ballerina.io/learn/user-guide/deployment/code-to-cloud/samples/
[4] https://github.com/ldclakmal/ballerina-samples/tree/master/c2c
