### ISSUE TITLE
SQL binding dosn't work for MySql date type

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-standard-library#3552]
Following code used to work in older versions (eg: 2201.1.1) but doesn't work in new (eg: 2201.2.0):
```ballerina
type MedicalNeed record {
    int itemID;
    time:Date period;
}

resource function get need() returns MedicalNeed|error {
    return check dbClient->queryRow(`SELECT NEEDID, PERIOD FROM MEDICAL_NEED WHERE NEEDID=1`);
}
```

With MySql table:
```sql
CREATE TABLE `medical_need` (
  `NEEDID` int NOT NULL AUTO_INCREMENT,
  `PERIOD` date NOT NULL,
);
```

Now gives following error:
```
error: The field 'period' of type Date cannot be mapped to the column 'PERIOD' of SQL type 'DATE'
```

Note this is a backward incompatible change form users perspective and will break some existing apps.

**Comment by niveathika** [comment]
@manuranga Could you let me sql version you are using with the distribution 2201.2.0?

I am unable to reproduce this with sql `1.5.0` in Ballerina `2201.2.0` distribution.

Due to the runtime breaking change(use of reference types), any sql versions  lower than `1.5.0` is incompatible with the distribution. Please clear the Dependencies.toml file and run the sample again.

**Comment by manuranga** [comment]
I am using mysql version '8.0.28'

**Comment by niveathika** [comment]
Could you check the `ballerina/sql` version in Dependencies.toml?
