### ISSUE TITLE
Add compiler validation to check entities are in a single module

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-standard-library#3810]
**Description:**
With the latest V2 design, entities can define only in one module. this task is to write a compiler plugin validator to check whether entities are in a single module.

Check the user experience in VSCode as well

**Comment by niveathika** [comment]
Due to the restriction of identifying the sub module with newly added entity (Compiler validation happens for each change, however we cannot identify the recent change that triggered the validations),

we decided to add a WARNING diagnostic to all valid entities in the package when entities are defined in more than one sub module.

@kalaiyarasiganeshalingam Could you work on the implementation?
