### ISSUE TITLE
Azure WebSubHub deployment not working properly after migrating to the new repository

### ISSUE THREAD

**Issue by ayeshLK** [ballerina-platform/ballerina-standard-library#3902]
**Description:**
After migrating to the new repository, the deployment fails for the `hub`. It is observed that the relevant port is not opened in the pod and hence the readiness and liveness checks are failing. Due to this `hub` pod is trapped in a crash-loop.

**Comment by ayeshLK** [comment]
Tested the deployment by disabling SSL and it was observed that it was working fine without SSL.

**Comment by chamil321** [comment]
As per Ayesh's observation, The websubhub listener is working fine when the SSL configs are removed. Also the ballerina version is also moved up from 2201.1.1 to 2201.2.3

Hence 
- listener is working on HTTP2 protocol (before 2201.2.0, it was HTTP1.1)
- Issue is only reproducible in cloud

There was a Netty related issue where, container need some non-readonly rights to `/tmp` dir.
https://github.com/wso2-enterprise/internal-support-ballerina/issues/207

In order to identify the issue locally needs to run the docker with `read only` flag.
Eg `docker run --read-only -p 9090:9090 <container id>`

**Comment by ayeshLK** [comment]
Tried running the docker container with `--read-only` flag along with the SSL configuration and the issue was reproduced locally. Since this is an issue with HTTP/2 protocol tried running the `hub` by providing the HTTP/1.1 for `httpVersion` configuration to the listener. And issue was resolved with that. Since, we don't have any hard requirement to run the deployment on HTTP/2, will update the code-base to run on HTTP/1.1.

**Comment by chamil321** [comment]
Downgrading the HTTP version is not the ideal solution. This issue can be fixed by mounting the `/tmp` dir with write access. I recommend it instead of the downgrading as we go along, many improvements will be done to HTTP2

**Comment by ayeshLK** [comment]
This task is completed with following PRs:
- https://github.com/wso2-enterprise/azure-websubhub/pull/16
- https://github.com/wso2-enterprise/azure-websubhub/pull/17
