### ISSUE TITLE
Need a constraint to validate Date/Time

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-standard-library#3960]
For example,
```java
@Past(message = "Birthdate should be in the past")
private LocalDate birthDate;
```

**Comment by TharmiganK** [comment]
# Proposed Solution

## Comparison with Java Bean Validation

The following constriants are available on the Date types in the Java Bean Validation:
| Annotation | Validation |
|------------|-----------|
| `@Past` | validate that a date value is in the past |
| `@PastOrPresent` | validate that a date value is in the past including the present |
| `@Future` | validate that a date value is in the future |
| `@FutureOrPresent` | validate that a date value is in the future including the present |

## Introduce a constraint on `time:Date` type

In contrast to the Java Bean Validation, the constraint annotations in Ballerina is binded to a **specific type rather than a specific constraint**. So the constraints in Ballerina is defined as the annotation record fields.

The Java Date type is equivalent to the Ballerina `time:Date` type. So we can allow a new annotation `@constraint:Date` on `time:Date` types.

### Definition

```bal
# The annotation, which is used for the constraints of the `time:Date` type.
annotation DateConstraints Date on type, field;

# Represents the constraints associated with `time:Date` type.
# 
# + isPast - If `true`, the date should be in the past.
# + isPastOrPresent - If `true`, the date should be in the past or present.
# + isFuture - If `true`, the date should be in the future.
# + isFutureOrPresent - If `true`, the date should be in the future or present.
type DateConstraints record {
    boolean isPast?;
    boolean isPastOrPresent?;
    boolean isFuture?;
    boolean isFutureOrPresent?;
};
```

### Sample usecase

```bal
type User record {|
    int id;
    string name;
    @sql:Column {name: "birth_date"}
    @constraint:Date {isPast: true}
    time:Date birthDate;
|};
```

> **Note:**
> - The `time` module provides a function to validate the date : [`time:dateValidate(Date date)`](https://lib.ballerina.io/ballerina/time/2.2.3#dateValidate). So adding this `constraint:Date` annotation will additionally validate date using this function implementation.
> - The constraint compiler plugin will validate the usage of this annotation on the attachment points as this is only allowed for `time:Date` types
> - With this change `constraint` module will have the dependency of `time` module and will use its native functions.

**Comment by TharmiganK** [comment]
The following are noticed while doing the implementation:

1. This is the definition of `time:Date` :

    ```bal
    type Date record {
      int year;
      int month;
      int day;
      int hour?;
      int minute?;
      decimal second?;
      readonly & record {|
        int hours;
        int minutes = 0;
        decimal seconds?;
      |} utcOffset?;
   };
   ```
   
   If we are allowing the `constraint:Date` on `time:Date` then we will be allowing the same annotation for sub types i.e. structurally similar types. For example:
   
   ```bal
   // Annotation will be allowed here. (If we check `CustomDate is time:Date` then it will be true)
   type CustomDate record {
      int year;
      int month;
      int day;
   }
   ```
   Implementation wise we only depend on the `year`, `month` and `day` fields. And other fields dont have any effect.
   We are only depending on `time` module in our compiler plugin and for testing
   So how do we proceed here? Are we going to depend on `time` module and allow the constraint annotation only on `time:Date`(If this is the case, this constraint won't be allowed for structurally equivalent types)?
   
2. Before doing any constraint validations with `isPast`, `isFuture`, etc. we need to first convert the `BMap` to a JAVA `LocalDate`, this can throw some exceptions if the date fields are not valid. So we are also validating the date. So I was thinking of allowing this `@constraint:Date` without any fields inorder to only validate the date. And we will be giving a constraint error. 
   
    ```bal
    type User record {|
        string name;
        @constraint:Date
        time:Date birthday;
    |};

    public function main() returns error? {
        User user = {
            name: "John",
            birthday: {
                year: 1999,
                month: 4,
                day: 31
            }
        };
        // error: Validation failed for '$.birthday.day:validate' constraint(s)
        user = check constraint:validate(user);
    }
    ```
    So shall we allow the following? Otherwise we might throw some error and terminate the constraint validation process when the date is not valid.
    
3. Since Ballerina supports constraints as a part of the annotation record fields, here we have allowed the fileds to be boolean. Because of that someone can set `isPast: false` and expects the date to be in future or present. This is same as making `isFutureOrPresent: true`. I was thinking of supporting both of them, and restrict the usage of the fields like you can set only one of the constraints: `isPast`, `isPastOrPresent`, `isFuture` or `isFutureOrPresent`. The restriction is because having more than of these constraint field can cause the following behaviours:
    - constraint fields can become redundant => `isPast: true` and `isFutureOrPresent: false`
    - constraint fields can become invalid => `isPast: true` and `isFutureOrPresent: true`
    - constraint fields can effectlively point to the present => `isPast: false` and `isFuture: false`

**Comment by TharmiganK** [comment]
@shafreenAnfar @daneshk @sahanHe and I had a call to discuss the above concerns and comeup with the following decisions.

1. We will be allowing `@constraint:Date` on any record which is structurally similar to this record :
    ```bal
    type Date record {
      int year;
      int month;
      int day;
    }
    ```
    
2. We will be allowing the `constraint:Date` without any fields which will validate the date fields. (This is similar to what we do in `time:validateDate` method)

3. Rather than having boolean fields we will be having an enum as a `option` field:
    ```bal
    # Represents the date option to be validated.
   # + PAST - validates whether the date is in the past
   # + PAST_OR_PRESENT - validates whether the date is in the past or present
   # + FUTURE - validates whether the date is in the future
   # + FUTURE_OR_PRESENT - validates whether the date is in the future or present
   enum DateOption {
       PAST,
       PAST_OR_PRESENT,
       FUTURE,
       FUTURE_OR_PRESENT
   }

   # Represents the constraints associated with `time:Date` type.
   #
   # + option - date option to be validated
   type DateConstraints record {
       DateOption option?;
   };
    ```
