### ISSUE TITLE
`RequestContext` does not include `Request`

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-standard-library#3964]
We need to fix it.

**Comment by TharmiganK** [comment]
We could allow `http:Request` as a parameter to the `interceptResponseError` remote method i.e.
```bal
service class ResponseErrorInterceptor {
  *http:ResponseErrorInterceptor;

  remote function interceptResponseError(error err, http:RequestContext ctx, http:Request req) 
      returns http:NextService|error? {
    io:println(req.rawPath);
    return ctx.next();
  }
}
```
@shafreenAnfar will this fulfill your requirement?

**Comment by TharmiganK** [comment]
Had a chat with @shafreenAnfar and @chamil321 and come up with the following options :

|Options|Pros|Cons|
|-----|-------|-----|
|1. Expose the `Request` as a parameter in the response path|- Easier to implement compared to other options|- This will expose unused setter methods in the response path</br>- This may make the `RequestContext` obsolete, since `Request` can be accessed directly in the response interceptors|
|2. Introduce a read-only version of the `Request` and expose that in the response path as a parameter|- This will hide the unnecessary setter methods and will expose only the required ones in read-only mode|- This can confuse the users since there are two versions of the request|
|3. Expose the required fields and getters of `Request` via `RequestContext`|- This will hide the unnecessary setter methods and will expose only the required ones|- These informations should be exposed only in response path, so accessing them in request path will not work|

**Comment by shafreenAnfar** [comment]
I think given that each has pros and cons, I feel the best option is 1, which results in the below.

Request path error handlers -> Request, RequestContext, error
Response path error handlers -> Response, Request, RequestContext, error

**Comment by chamil321** [comment]
> I think given that each has pros and cons, I feel the best option is 1, which results in the below.
> 
> Request path error handlers -> Request, RequestContext, error Response path error handlers -> Response, Request, RequestContext, error

+1. I also think the same. Using the request at response path error handlers are not very frequent and the impact from changing the values of the request at this level is also minimum.
