### ISSUE TITLE
[GraphQL] Possibility of using the same Ballerina record as gql input and output objects

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-standard-library#4194]
**Description:**
GraphQL has two different types to represent input and output. In the case of Ballerina, we don't have such concept, we only have Records and Objects. In general, one could use the same record for input and output. At the moment, this mismatch is handled by not allowing the same record to be used for both input and output. Ballerina complier gives a compilation error in this case.

This issue is to see, instead, if we can maybe let the user use the same record/object and then generate gql type. 

@ThisaruGuruge @MohamedSabthar @DimuthuMadushan

**Comment by ThisaruGuruge** [comment]
Let me first define the issue first for the references.

In a GraphQL schema, `INPUT_OBJECT` and `OUTPUT_OBJECT` (usually called `OBJECT`) have two different semantic meanings. 

Although both types can have fields, the `OUTPUT_OBJECT` fields can have input arguments, can implement interfaces, can be a member of a union type, etc. `INPUT_OBJECT` cannot be any of these things. Therefore, although the structure may look similar, these two types are defined to do completely different things. Therefore, the [GraphQL spec does not allow](https://spec.graphql.org/October2021/#sec-Input-and-Output-Types) using the same type as an `INPUT_OBJECT` and an `OUTPUT_OBJECT`.

In Ballerina, we use
- `record` types to define `INPUT_OBJECT` types.
- `record` and `service` types to define `OUTPUT_OBJECT` types.

Confusion occurs when there are similar structures in the `INPUT` and `OUPUT` object types. As mentioned in the issue, it seems that we can define both types using the same Ballerina type sometimes.

A main point to note is that while the Ballerina type system is structural, the GraphQL type system is nominal. 

In this case, if we are to allow using the same Ballerina type for the `INPUT` and the `OUTPUT`, we have to use generated type names instead of the user-defined types in the GraphQL schema. This can cause multiple problems for the developers.

- When a GraphQL service is introspected, the introspection query will return types that are not available in the server code.
- In GraphQL responses, some error messages contain type information (such as querying invalid fields in `OUTPUT_OBJECT` types, missing required fields in an `INPUT_OBJECT` type). This might cause confusion since the type names in the server and the error messages are different. 
- Generating type names can cause more issues since there can be type name clashes, which we may not predict and then the whole schema generation will fail. 

Apart from the above reasons, in GraphQL, it is considered a [best practice](https://www.apollographql.com/blog/graphql/basics/designing-graphql-mutations/) to define an `INPUT_OBJECT` per each mutation and use it as the single input parameter type for a given mutation operation.

Given these reasons, IMHO, I don't think allowing to use the same record type as an `INPUT_OBJECT` and an `OUTPUT_OBJECT` brings much value to the DX, compared to the issues it causes.
