### ISSUE TITLE
Requesting the union type support for resource Path parameters

### ISSUE THREAD

**Issue by lnash94** [ballerina-platform/ballerina-standard-library#4216]
**Description:**
While generating the connectors we found an API the path parameter can be either an integer or a string. The current resource function didn't support the union type. It gives compilation time errors. Therefore this issue is to request union path parameter support resource functions. 
Reference API: https://qdrant.github.io/qdrant/redoc/index.html#tag/collections/operation/get_snapshot
Reference OAS spec: https://github.com/qdrant/qdrant/blob/master/docs/redoc/master/openapi.json#L1981
 
**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by lnash94** [comment]
When we wrote **a service with resource functions with a union path parameter** [1] it gives a compilation error [2] 
[1] http service with a union path parameter
```ballerina
import ballerina/http;
service / on new http:Listener(9090) {

    resource function get pet/[string|int id]() returns string {
        return "Hi there..";
    }
}
```
[2] compilation error for service resource 
```
error: incompatible path parameter type: ''
```

If we wrote **client with resource method with union path parameter**[3] it doesn't give a compilation error
[3] client with union resource path parameter
```ballerina
import ballerina/http;

public isolated client class Client {
    final http:Client clientEp;
    
-----
    resource isolated function get pet/[int|string id]() returns string|error {
        string resourcePath = string `/pet/${id}`;
        string response = check self.clientEp->get(resourcePath);
        return response;
    }
}
```
As mentioned in the parent issue https://github.com/ballerina-platform/ballerina-standard-library/issues/4216#issue-1627054858  we found API which allows union type as a path parameter. Therefore current connector code generation has no issue with union-type data binding since we generate endpoint URLs inside the resource method.

 @shafreenAnfar, @TharmiganK Could you please verify whether these two behaviour is expected or if both client and service resource should have the same behaviour either supporting union type path parameter or not supporting?

**Comment by TharmiganK** [comment]
In the service example, actually we are not giving any compiler errors from our side the resource path segments are validated from the lang compiler. The error you are getting is a runtime error which was thrown when creating the resource object. So from HTTP side we **only allow one of the basic type**(`string`, `int`, `decimal`, `float`, `boolean`) **or an array of that type**. **But we missed to check this through our compiler plugin. This should be fixed since the runtime error is also meaningless without the type.**

In the client example, what you have written is a ballerina client class and according to the lang spec it allows path parameter to be a sub type of `string|int|decimal|float|boolean`. 

And if you consider about the line where you call the HTTP client from the above client, currently we **only allow path segments to be string** so you **cannot do this** :
```bal
string response = check self.clientEp->/path/[id]; //Compiler error
response = check self.clientEp->/path/[id.toString()]; //This will work
```

So if we are allowing union types in the service resource functions, they we have to add the support in the client resource calls as well to be consistent. @shafreenAnfar WDYT?

**Comment by shafreenAnfar** [comment]
Yeah, we need to fix both sides.

**Comment by TharmiganK** [comment]
Identified a problem in supporting this for the service. We are converting the path string with respect to the type defined in the resource signature. So if we allow union type, then it will create an ambiguity in resolving the type.

Lets say the service is defined like this:
```bal
service on new http:Listener(9090) {

    resource function get test/[string|int|float path]() returns string {
        return "Test!";
    }
}
```

Consider the following scenarios:
1. `curl http://localhost:8080/test/hello` -> No ambiguity since the value `hello` cannot be converted as `int` or `float`
2. `curl http://localhost:8080/test/45.87` -> Now the string value "45.87" can be converted as `string` as well as `float`
3. `curl http://localhost:8080/test/45` -> Now the string value "45" can be converted to `string`, `int` and `float`

If we are going to support this there should be a priority order to resolve this ambiguity. @shafreenAnfar is there any other way to resolve this?

**Comment by shafreenAnfar** [comment]
Shall we organise a call with @lnash94 to understand requirement. I am struggling to understand what type of API actually needs this.

**Comment by TharmiganK** [comment]
Had a call with @lnash94 and @shafreenAnfar and came to the following conclusions:

1. We are not going to support union types as a resource path parameter in the **service**. Since what we get from the url is just the string path segment and from that value it is not possible to find the exact type if we are using union types. So **we will be only allowing a single basic type as path parameter and will give proper compiler error from our plugin**.

2. We will be **improving http client to have union basic typed resource path segments**. Since this is useful in case you are invoking a client call with the union type. This can be even achieved by converting the type to string.

```bal
import ballerina/http;

public isolated client class Client {
    final http:Client clientEp;
    
-----
    resource isolated function get pet/[int|string id]() returns string|error {
        // string resourcePath = string `/pet/${id}`;
        // string response = check self.clientEp->get(resourcePath);
        // string response = check self.clientEp->/pet/[id.toString()]; // This will work
        string response = check self.clientEp->/pet/[id]; //This will be supported
        return response;
    }
}
```

**Comment by TharmiganK** [comment]
Closing this issue since the conclusion made from this issue is merged to the master
