### ISSUE TITLE
CORS error on put request to localhost

### ISSUE THREAD

**Issue by SasikaSankalana** [ballerina-platform/ballerina-standard-library#4236]
**Description:**

When using PUT method I'm getting this error.

> Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Ballerina server doesn't identify my put request as the corresponding resource.

This is my ballerina service code

```bal
import ballerina/http;

@http:ServiceConfig {
    cors: {
        allowOrigins: ["http://localhost:3000"],
        allowMethods:["GET","POST","PUT","DELETE","OPTIONS"]
    }
}

service /projects on new http:Listener(8080) {


    isolated resource function post .(@http:Payload Project project) returns int|error? {
        return addProject(project);
    }

    isolated resource function get [int id]() returns Project|error? {
        return getProject(id);
    }

    isolated resource function get .() returns Project[]|error? {
        return getAllProjects();
    }

    isolated resource function put .(@http:Payload Project project) returns int|error? {
        return updateProject(project);
    }

    isolated resource function delete [int id]() returns int|error? {
        return removeProject(id);
    }

}
```

**Comment by TharmiganK** [comment]
@SasikaSankalana I believe you are not getting the `Access-Control-Allow-Origin` header when you make a preflight request to this `PUT` resource: `/projects/1`. And this is the actual response you are getting from this service:
```console
HTTP/1.1 204 No Content
allow: GET, DELETE, OPTIONS
content-length: 0
server: ballerina
date: Tue, 21 Mar 2023 11:03:14 +0530, 0B
```

This is expected as there is no resource matching `projects/1` in you service. If you are referring to this `PUT` resource:
```bal
isolated resource function put .(@http:Payload Project project) returns int|error? {
     return updateProject(project);
}
```
Then this is not bind to `/projects/[id]`, this is actually bind to `/projects`[1]. Since the requested resource does not exist you are not getting the `Access-Control-Allow-Origin` header.

If you change your resource like this then it should work:
```bal
isolated resource function put [int id](@http:Payload Project project) returns int|error? {
     return updateProject(project);
}
```

[1] https://ballerina.io/learn/by-example/http-service-and-resource-paths/

**Comment by SasikaSankalana** [comment]
Thank you. It solved my issue.
