### ISSUE TITLE
Rewrite the log package in Ballerina

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-standard-library#429]
**Description:**
Currently the Ballerina log API is implemented as native functions. Need to rewrite this in Ballerina itself so that the dependency to JDK logging can be removed.

**Comment by MadhukaHarith92** [comment]
JDK logging dependency is removed in https://github.com/ballerina-platform/module-ballerina-log/pull/116. However, there are still some java interop functions because,
1. Need to write the log output to the STDERR stream and currently, this is not possible with Ballerina.
2. Need to set log levels to a map (module log levels) and retrieve values. Since the log module functions are isolated this operation cannot be done (Cannot access mutable storage inside isolated functions).
