### ISSUE TITLE
Requesting open record support for query parameter

### ISSUE THREAD

**Issue by lnash94** [ballerina-platform/ballerina-standard-library#4541]
**Description:**
We encountered the compilation issue when writing a code with an open record query parameter in the service. Most of the time in openAPI spec we receive open records as query parameters. Below are the scenarios we encounter 

Scenario 01: Query parameter has open record type definitions
```ballerina
public type User record {
    int id;
    string name;
};
service /lnash94/QueryParam/'1\.0\.0 on ep0 {
      resource function post inventory(User user) returns http:Created {
        ...
        return <http:Created> {};
    }
}
```

Scenario 02: Query parameter has an inline open record.
```ballerina
service /lnash94/QueryParam/'1\.0\.0 on ep0 {
      resource function post inventory(record { int id; string name;} user) returns http:Created {
        ...
        return <http:Created> {};
    }
}
```
Scenario 03: Query parameter has inline closed record open with record values.
```ballerina
public type User record {
    int id;
    string name;
};
service /lnash94/QueryParam/'1\.0\.0 on ep0 {
      resource function post inventory(record{|User...;|} user) returns http:Created {
        ...
        return <http:Created> {};
    }
}
```
Scenario 04: Query parameter has nested record inside.
```ballerina
public type User record {
    int id;
    string name;
    Address address;
};

public type Address record {
    int no;
    string street;
};
service /lnash94/QueryParam/'1\.0\.0 on ep0 {
      resource function post inventory(User user) returns http:Created {
        ...
        return <http:Created> {};
    }
}
```
**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by TharmiganK** [comment]
Since we are anyway allowing `anydata` in the payload, we should be able to allow an object query as a `map<anydata>`. We need to add the support from the compiler plugin as we are currently only allowing `map<json>` structures. If we do that then open records will be allowed as query params if there are structurally similar to `map<json>` (Records cannot have non-anydata files like ballerina object)

The conversion might fail if we have non-json fields in the decoded query string. Then for those requests we will be sending a `400 - Bad Request` as we only allow json compatible fields in the query object.

@dilanSachi FYI
