### ISSUE TITLE
[Bug]: Experiencing a processing delay when call multiple request to the SQL DB

### ISSUE THREAD

**Issue by bpriyabhashana** [ballerina-platform/ballerina-standard-library#4597]
### Description

Experiencing a response delay when calling multiple times to the DB in the same API request. 
As per the requirement, with one API request it calling multiple times to the DB with different executions.  

Permalink to the mentioned API : https://github.com/wso2-enterprise/digiops-sales/blob/7ae876769976f1e8f08b0bebfdc04bc633a75159/apps/certification_admin_portal/bff/service.bal#L402

As a workaround 

- Tried by breaking down the API into separate APIs. But the sum of the processing time of all APIs is almost same with the previous execution time.

- Then tried with replacing single row execution with `batchExecute`.  With this was able to replace 30 separate row insert into 1 batch execution. 
But the execution time is same as before. 

https://github.com/wso2-enterprise/digiops-sales/pull/350

### Affected Version(s)

2201.5.0

### Related area

-> Compilation

**Comment by kalaiyarasiganeshalingam** [comment]
The different hosted regions of Choreo PDP and Azure DB caused this issue. The problem is sorted now by changing both hosts to the same region.

Current Setup
Choreo PDP (US East 2) | Azure DB (Southeast Asia)
-- | --

<br class="Apple-interchange-newline">

After created a Azure DB in same region as of Choreo PDP
Choreo PDP (US East 2) | Azure DB (US East 2)
-- | --


<br class="Apple-interchange-newline">


As a result, we were able to reduce the processing time from 53.8 seconds to 2.46 seconds
Choreo PDP (US East 2) | Azure DB (Southeast Asia) | 53.85076852 s
-- | -- | --
Choreo PDP (US East 2) | Azure DB (US East 2) | 2.46 s

<br class="Apple-interchange-newline">
