### ISSUE TITLE
Enable Ocsp Tests with Java 17

### ISSUE THREAD

**Issue by warunalakshitha** [ballerina-platform/ballerina-standard-library#4695]
**Description:**
Those were failed with Java 17. 
https://github.com/ballerina-platform/module-ballerina-http/pull/1720

**Comment by TharmiganK** [comment]
The tests are failing due to this exception: [java.lang.ClassNotFoundException: com/sun/security/cert/internal/x509/X509V1CertImpl exception](https://stackoverflow.com/questions/74698707/java-lang-classnotfoundexception-com-sun-security-cert-internal-x509-x509v1cert)

This seems to happen since we use deprecated classes and methods. So updating them should fix these test failures
