### ISSUE TITLE
Driver cannot connect to the MSSQL server after migrating to Java 17

### ISSUE THREAD

**Issue by sahanHe** [ballerina-platform/ballerina-standard-library#5065]
**Description:**
Currently when tried to connect to the the MSSQL databased using module-ballerina-mssql, it fails with the following error
```
error: Error in SQL connector configuration: Failed to initialize pool: The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "PKIX path building failed: unable to find valid certification path to requested target". ClientConnectionId:4036508b-8f55-4fa6-bbf4-743389988323 Caused by :The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. 
```

this started after updating to mssql driver version 10.2 - [release note](https://techcommunity.microsoft.com/t5/sql-server-blog/jdbc-driver-10-2-for-sql-server-released/ba-p/3100754)

**Affected Versions:**
module-ballerina-mssql.driver : 1.6.0

**Comment by kaneeldias** [comment]
This is due to the later mssql jdbc driver we are using (10.2)

According to the [release note](https://techcommunity.microsoft.com/t5/sql-server-blog/jdbc-driver-10-2-for-sql-server-released/ba-p/3100754), the following breaking changes were made

- BREAKING CHANGE - Default Encrypt to true
- BREAKING CHANGE - Changed certificate validation behavior to validate when encryption is negotiated from either the client or the server

Now the default values for the connection properties `encrypt` and `trustServerCertificate` is set to `true` and `false` respectively. Which was not the behaviours we expected when using the older drivers
