### ISSUE TITLE
Add support for Constraint on the floating point count

### ISSUE THREAD

**Issue by DimuthuMadushan** [ballerina-platform/ballerina-standard-library#5081]
**Description:**
>$subject

Add support for Constraint on the floating point count in Constraint module. This may help to limit the number of a digits in a floating point number.

**Comment by TharmiganK** [comment]
The requested feature is similar to,
- [`@Digits` constraint annotation in Java](https://javaee.github.io/javaee-spec/javadocs/javax/validation/constraints/Digits.html)
- [`totalDigits`](https://www.w3.org/TR/xmlschema-2/#dc-totalDigits) and [`fractionDigits`](https://www.w3.org/TR/xmlschema-2/#dc-fractionDigits) rules in XML schema

<h1>The proposed constraints</h1>

| Constraint name | Applies to constraint type | Constraint value type | Semantics (`v` is value being constrained, `c` is constraint value) |
| ----------------- | --------------- | --------------------- | -------------------------------------------------------------- |
| `maxDigits`   | `@constraint:Int` | positive integer | number of digits in `v` <= `c` |
| `maxIntegerDigits` | `@constraint:Float`, `@constraint:Number` | positive integer | number of digits in the integer part of `v` <= `c` |
| `maxFractionDigits` | `@constraint:Float`, `@constraint:Number` | positive integer | number of digits in the fraction part of `v` <= `c` |

<h2>Usage</h2>

```bal
@constraint:Int {maxDigits: 4}
type Integer int;

@constraint:Float {maxIntegerDigits: 3, maxFractionDigits: 2}
type Float float;

@constraint:Number {maxFractionDigits: 3}
type Number int|decimal|float;
```

<h2> Additional validations </h2>

- The value of the above constraint should be a **positive integer**. This validation will be done by the compiler plugin, if the value is provided inline. Otherwise, an error will be returned at runtime when we call `validate`. 

@shafreenAnfar Can you review?

**Comment by TharmiganK** [comment]
This constraint is also allowed on the built-in sub types of `int` such as `int:Unsigned8`, `int:Unsigned16`, `int:Unsigned32`, `int:Signed8`, `int:Signed16` and `int:Signed32`. All these types has a digit limit according to their representation. The validation between that limit and the value provided by the constraint, is not performed at compiler time. But at runtime it will fail when we do value to type conversion(by `cloneWithType` which is called internally when we call `validate` method).
This behaviour is same as what we do for `maxValue` and `minValue`.

```ballerina
import ballerina/constraint;
import ballerina/log;

@constraint:Int {maxDigits: 4} // No compiler error
type Integer int:Signed8;

public function main() {
    // int:Signed8 a = 1000; // Compiler error from Lang

    Integer|error b = constraint:validate(1000); // No compiler error
    if b is error {
        // Type conversion failed due to typedesc and value mismatch.
        log:printError("error occurred", b);
    }
}
```

**Comment by lnash94** [comment]
> This constraint is also allowed on the built-in sub types of `int` such as `int:Unsigned8`, `int:Unsigned16`, `int:Unsigned32`, `int:Signed8`, `int:Signed16` and `int:Signed32`. All these types has a digit limit according to their representation. The validation between that limit and the value provided by the constraint, is not performed at compiler time. But at runtime it will fail when we do value to type conversion(by `cloneWithType` which is called internally when we call `validate` method). This behaviour is same as what we do for `maxValue` and `minValue`.
> 
> ```ballerina
> import ballerina/constraint;
> import ballerina/log;
> 
> @constraint:Int {maxDigits: 4} // No compiler error
> type Integer int:Signed8;
> 
> public function main() {
>     // int:Signed8 a = 1000; // Compiler error from Lang
> 
>     Integer|error b = constraint:validate(1000); // No compiler error
>     if b is error {
>         // Type conversion failed due to typedesc and value mismatch.
>         log:printError("error occurred", b);
>     }
> }
> ```

Does it validate the given value type during the runtime (ex: check whether it is signed32 or signed64) or its constraint validations (ex: check it exceeds or has constraint rules max digits )?

**Comment by TharmiganK** [comment]
> Does it validate the given value type during the runtime (ex: check whether it is signed32 or signed64) or its constraint validations (ex: check it exceeds or has constraint rules max digits )?

When we call the `validate` method, the first step is to clone the value with the type provided by the `typedesc`. Then only we execute the constraint validations.

For example, `Integer|error b = constraint:validate(1000);` here the `typedesc` is `Integer` which is a subtype of `int:Signed8`. So we first try to clone the value `1000` to this type. Then it will fail since the `int:Signed8` cannot have a value greater than `127`. Hence we return this error: `Type conversion failed due to typedesc and value mismatch.`

**Comment by lnash94** [comment]
Thank you @TharmiganK for the clarification. I'm wondering about the behaviour regarding the **minDigits** scenario[1]
```ballerina
@constraint:Int {minDigits: 4} 
type Integer int:Signed8;

public function main() {
    Integer|error b = constraint:validate(100); 
}
```
may this behave like the **minimum** in an integer value with `int:Signed8`?

**Comment by TharmiganK** [comment]
> I'm wondering about the behaviour regarding the **minDigits** scenario
> may this behave like the **minimum** in an integer value with `int:Signed8`?

This proposal only covers the `maxDigits` constraint. I have not seen `minDigits` constraint in Java or XML schema. I think there are no actual use cases for that constraint. If it is requested we could support that.

But I could understand the concern when there is a `minValue` constraint on integer subtypes:
```ballerina
// The constraint value is not correct since `int:Signed8` cannot have values greater than 128
// Still we do not report a compiler error. This could be a compiler plugin validation
@constraint:Int {minValue: 128}
type Integer int:Signed8;

public function main() {
    Integer|error b = constraint:validate(102);
    // This will give an error saying validation failed for `minValue`
    // But actually we should give an error saying the value for `minValue` 
    // is not compatible with the type
}
```
We can create another issue to address this as an improvement
