### ISSUE TITLE
GraphQL support at Ballerina language level

### ISSUE THREAD

**Issue by nuwanbando** [ballerina-platform/ballerina-standard-library#540]
This would be a great addition to retrieve data from data sources and expose them as POST-Query enabled services. - https://graphql.org/

**Comment by ThisaruGuruge** [comment]
**Closing the issue since the module is now available**

Ballerina Standard Library now includes a GraphQL module. Although it supports basic use cases, this is still work in progress. 

Please create issues for any feature requests and/or bugs in the [Ballerina Standard Library repo](https://github.com/ballerina-platform/ballerina-standard-library). 
- [GraphQL module source](https://github.com/ballerina-platform/module-ballerina-graphql)
- [Existing issues related to Ballerina GraphQL module](https://github.com/ballerina-platform/ballerina-standard-library/issues?q=is%3Aissue+is%3Aopen+label%3Amodule%2Fgraphql)
- [Ballerina GraphQL API documentation](https://ballerina.io/learn/api-docs/ballerina/#/ballerina/graphql/latest)
