### ISSUE TITLE
Check on any possibility to remove LinkedList from the cache impl

### ISSUE THREAD

**Issue by kalaiyarasiganeshalingam** [ballerina-platform/ballerina-standard-library#722]
$Subject

**Comment by kalaiyarasiganeshalingam** [comment]
**Description**

The following external libs used to analyze the current cache module implementation without a linked list. 
- Apache concurrentLinkedHashMap
- Google code  concurrentLinkedHashMap
- Caffeine cache

I have also done the performance test for the below scenarios using the above libs. 
- Pure cache test
- HTTP caching
- Http with JWT

You can find those result in this sheet
[https://docs.google.com/spreadsheets/d/1z6Ypxx8GkK9pABqoG6d495if-B4oNjLRgbLlKUnCfng/edit#gid=0](https://docs.google.com/spreadsheets/d/1z6Ypxx8GkK9pABqoG6d495if-B4oNjLRgbLlKUnCfng/edit#gid=0)

**Observation**

When we used concurrentLinkedHashMap, we got the cache performance test result higher than the existing implementation by twofold. Even though the HTTP performance test result also has improved but there is no relatively significant change.

**Conclusion**

We can improve the cache module with concurrentLinkedHashMap if we want.

**Comment by ben-manes** [comment]
I am not familiar with your work, so I apologize for jumping in, but I see a took a glance at the [cache benchmark](cache-performance.bal). This tests with a uniform distribution which minimizes the chance of lock contention, but also has no recency/frequency characteristics for an eviction policy to exploit. Thus random replacement is ideal and it might give a false impression. I use a Zipfian distribution in a [JMH benchmark](https://github.com/ben-manes/caffeine/wiki/Benchmarks#read-100) to better model multiple threads accessing the same hot entries.

It may be that the http benchmark suffered from Caffeine's default behavior of deferring the policy maintenance to a background thread (`ForkJoinPool.commonPool()`). This is used for any asynchronous work, so the policy maintenance is deferred to avoid penalizing the caller from incurring user-facing latencies. For example an eviction listener might be configured and the cache is unaware how expensive that user code may be. In normal operations using the common pool has no negative impact and might improve latencies, as typically a server's cpu isn't maximized. In a benchmark, however, this could be wasteful by adding context switching as threads fight for cpu time. You may observe a small gain by using `Caffeine.executor(Runnable::run)` to perform the "async" work on the calling thread.

I believe the only difference that Apache made to CLHM is (1) adding compute methods and (2) replacing the backport of JDK8's ConcurrentHashMap to be compiled on JDK8 instead. Since CLHM is small it is nice to fork and embed, so I think it is mostly identical for your purposes.

Some aspects of Caffeine should be faster, but it might also be slower in cpu time due to the additional features. A slightly higher hit penalty for much fewer cache misses would be favored in real systems, so LRU is replaced by a more advanced algorithm. Of course if your workload is strongly recency-biased then LRU is optimal, but to be robust the cache implements a policy that is near optimal in any workload pattern (LRU, LFU, MRU). You might not observe that benefit in a concurrency benchmark.

Your custom cache may suffer from LRU list corruption. While the list operations are guarded by a tryLock and skipped if locked, that could result in a few odd scenarios:
1. On a [get](https://github.com/ballerina-platform/module-ballerina-cache/blob/e2af078fcb005c64b2abc3e59b11d691048ac944/cache-ballerina/lru_eviction_policy.bal#L32-L35) the [remove](https://github.com/ballerina-platform/module-ballerina-cache/blob/e2af078fcb005c64b2abc3e59b11d691048ac944/cache-ballerina/linked_list.bal#L85-L103) succeeds but the [addFirst](https://github.com/ballerina-platform/module-ballerina-cache/blob/e2af078fcb005c64b2abc3e59b11d691048ac944/cache-ballerina/linked_list.bal#L65-L80) does not. Now the entry is outside of the LRU list and may never be evicted from the `ConcurrentHashMap`.
2. The LRU victim may be concurrently evicted while another thread reads it. This mirrors (1) where the evict's remove may be cancelled by the `get` calling `addFirst`.
3. When the entry fails to be removed, then the cache exceeds its capacity. The `size() == maxSize` check for triggering eviction will no longer become true, so the cache will never size evict again until expiration "fixes" the state due to a full sweep.

That design might be acceptable for your use-case, but is also a bit surprising by relying on a periodic fixup to avoid runaway growth. You may wish to document that and not allow for expiration to be disabled, or else risk runaway growth.

**Comment by daneshk** [comment]
@ben-manes Thanks a lot for your insight. This is really helpful for us to evaluate further. We also identified the issue in our cache implementation, which leads to LRU list corruption. We are looking for the best solution for our cache design. 

We will have another look. Again thanks for jumping in and providing your valuable insight.

**Comment by kalaiyarasiganeshalingam** [comment]
@ben-manes Thank you very much for pointing out those and spending your valuable time. Yes, we have an issue with our existing implementation. Therefore, I did some research to improve. Your thoughts and suggestions will definitely help me to analyze further. Thanks a lot, again.

**Comment by kalaiyarasiganeshalingam** [comment]
Removed in [#72](https://github.com/ballerina-platform/module-ballerina-cache/pull/72)
