### ISSUE TITLE
[Discussion] HTTP service usability issues

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-standard-library#726]
1. Both service absolute path and resource function name look inconsistent.  `/` is a must for absolute path and resource name cannot have single `/`. IMO that is not a very intuitive approach where URL matching to a `.`(internally we use `/`, but user doesn't see it). 
```ballerina
service http:Service /hello on ep {
    resource function 'default .(http:Caller caller, http:Request req) {
        //...
    }
}
```
2. Other thing is resource name cannot start with `/`. Either we should remove it from the absolute path or have `/` in the beginning to resource path.
```ballerina
service http:Service /hello on ep {
    resource function get world(http:Caller caller, http:Request req) {
        //...
    }
}
```
3. Accessor has restricted resources to use either one method or all methods(using `default` term). GET and HEAD could treat the same way in a resource. But not possible with accessor restrictions. Expecting something like the following?
```ballerina
service http:Service /hello on ep {
    resource function [get,head] world(http:Caller caller, http:Request req) {
        //...
    }
}
```

**Comment by shafreenAnfar** [comment]
Point 1) I know it is a bit different from what we've been doing but `.` seems fine to me. It simply represents current location of the path. Similar to file-paths. 

Point 2) Yeah, I also agree. It is better to start the resource name as `/world`. I was under the impression that we could already do this. 
@hasithaa @rdhananjaya Any idea ?

**Comment by hasithaa** [comment]
Shall we raise point 2 in the spec? I also feel better to have `/` before the resource-path-segment or having `/` at the end of the absolute-path segment. 

For point 3: That is intentional, These are accessor qualifiers, which describes how you access the resource. For example, You can't do both get and set in the same method in an object, because logic is different. The same principle applies to resources. There can be exceptions, but since it is not a prominent case, we kept only a single accessor qualifier.

**Comment by chamil321** [comment]
Thanks for your inputs. [Created an issue for point 2 ](https://github.com/ballerina-platform/ballerina-spec/issues/673)
