### ISSUE TITLE
io:openWritableFile() method doesn't support overwriting the content of a file

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-standard-library#878]
When overwriting the content of a file, we can pass `append=false` as the 2nd parameter to `io:openWritableFile()` method. However, this doesn't empty the content of the file before writing the new content. 

For example, suppose we have the following content in a json file:
```
{
    "wines": [
        {
            "id": 1,
            "name": "Wine 1",
            "color": "Red",
            "country": "LKA"
        },
        {
            "id": 2,
            "name": "Wine 2",
            "color": "Yellow",
            "country": "FRA"
        }
    ]
}
```

and we want to add `{"id":3, "name":"Wine 3", "color":"Purple", "country":"Australia"}` to the `wines` array. To perform that, we read the file as a json, then add the above object to the json array and write it back to the file. In this scenario we need to perform an overwrite instead of appending. When we use `io:fileWriteJson(dataPath, data)` or `io:openWritableFile(dataPath, false)`, we get the following output:
```
{"wines":[{"id":1, "name":"Wine 1", "color":"Red", "country":"LKA"}, {"id":2, "name":"Wine 2", "color":"Yellow", "country":"FRA"}, {"id":3, "name":"Wine 3", "color":"Purple", "country":"Australia"}]}ine 2",
            "color": "Yellow",
            "country": "FRA"
        }
    ]
}
```
Notice the original content remains partially without being overwritten.

**Expected Behavior**
In case of `io:openWritableFile()` it should allow us overwriting the content of a file with new content when `append` is `false`.

**Comment by BuddhiWathsala** [comment]
The reason for this behavior is the specified file opened without Java [StandardOpenOption.TRUNCATE_EXISTING](https://docs.oracle.com/javase/7/docs/api/java/nio/file/StandardOpenOption.html#TRUNCATE_EXISTING). To solve this, we can follow 3 approaches:

**Approach 01**
Enable StandardOpenOption.TRUNCATE_EXISTING by default for non-appending scenarios. 

**Approach 02**
Add a boolean param to specify this. But it would make the open API more complex.

**Approach 03**
Introduce enum options, that users can specify a set of options that they need.

Since we are in alpha releases, we planned to go ahead with Approach 01, since truncating is the obvious use case and it won't break the API. However, going forward, we are planning to support Approach 03.
