### ISSUE TITLE
Compare sprintf function with String template literal

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-standard-library#982]
Compare `sprintf` function with the string template support in Ballerina Language and check whether we can replace `sprintf` with string template.

**Comment by BuddhiWathsala** [comment]
### Case 01
```ballerina
boolean v1 = false;
string s1 = io:sprintf("This is a boolean: %b", v1);
// s1 => This is a boolean: false
string r1 = string `This is a boolean: ${v1}`;
// r1 => This is a boolean: false

```
Outputs are similar.

### Case 02
```ballerina
boolean v2 = true;
string s2 = io:sprintf("This is a boolean in all caps: %B", v2);
// s2 => This is a boolean in all caps: TRUE
string r2 = string `This is a boolean in all caps: ${v2.toString().toUpperAscii()}`;
// r2 => This is a boolean in all caps: TRUE
```
Had to do an upper case conversion in the string template case.

### Case 03
```ballerina
int v3 = 8;
string s3 = io:sprintf("This is an integer: %d", v3);
// s3 => This is an integer: 8
string r3 = string `This is an integer: ${v3}`;
// r3 => This is an integer: 8
```
Outputs are similar.

### Case 04
```ballerina
float v4 = 8.504;
string s4 = io:sprintf("This is a float: %f", v4);
// s4 => This is a float: 8.504000
string r4 = string `This is a float: ${v4}`;
// r4 => This is a float: 8.504
```
Outputs are almost similar except for the tailing zeros in the string template case.

### Case 05
```ballerina
float v5 = 8.506;
string s5 = io:sprintf("This is a float with 2 places after decimal points: %.2f", v5);
// s5 => This is a float with 2 places after decimal points: 8.51
string r5 = string `This is a float with 2 places after decimal points: ${v5.round()}`;
// r5 => This is a float with 2 places after decimal points: 9.0
```
Outputs are different due to the lack of the API support mentioned here(https://github.com/ballerina-platform/ballerina-lang/issues/28804). However, we could make these outputs similar by using the mentioned workaround here(https://github.com/ballerina-platform/ballerina-lang/issues/28804).

### Case 06
```ballerina
int v6 = 0X3DF;
string s6 = io:sprintf("This is a hexadecimal: %x", v6);
// s6 => This is a hexadecimal: 3df
string r6 = string `This is a hexadecimal: ${v6.toHexString()}`;
// r6 => This is a hexadecimal: 3df
```
To make these values similar, we had to convert the integer representation of the hex value to a string.

### Case 07
```ballerina
int v7 = 0X3DF;
string s7 = io:sprintf("This is a hexadecimal in all caps: %X", v7);
// s7 => This is a hexadecimal in all caps: 3DF
string r7 = string `This is a hexadecimal in all caps: ${v7.toHexString().toUpperAscii()}`;
// r7 => This is a hexadecimal in all caps: 3DF
```
Need to do a hex string conversion and an upper case conversion to make these outputs similar.

### Case 08
```ballerina
string v8 = "Ballerina";
string s8 = io:sprintf("This is a string: %s", v8);
// s8 => This is a string: Ballerina
string r8 = string `This is a string: ${v8}`;
// r8 => This is a string: Ballerina
```
Outputs are similar.

### Case 09
```ballerina
int v9 = 8;
string s9 = io:sprintf("This is an int with leading zeros: %09d", v9);
// s9 => This is an int with leading zeros: 000000008
string r9 = string `This is an int with leading zeros: 00000000${v9}`;
// r9 => This is an int with leading zeros: 000000008
```
Need to manually add these heading zeros in the string template case.

### Summary
Most of the sprintf use cases are easily replicated using string templates. But the following use cases need some extra effort before achieving a similar sprintf output.
- convert boolean to all caps
- round a float value
- all hexadecimal use cases
- adding heading zeros

**Comment by daneshk** [comment]
Based on the latest discussion, we decided to remove `sprintf` function from the `io` module. Instead, use a string template literal. We need to communicate this in the dev group. @BuddhiWathsala please note.

**Comment by BuddhiWathsala** [comment]
Close this since we are going to remove the `io:sprintf` API.
